# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/FINN_build_mlp27k_w4a8_ft_clean/vivado_stitch_proj_8ba8a6h2/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/ip/finn_design_Thresholding_Batch_0_0/finn_design_Thresholding_Batch_0_0.xci
# IP: The module: 'finn_design_Thresholding_Batch_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/FINN_build_mlp27k_w4a8_ft_clean/vivado_stitch_proj_8ba8a6h2/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/ip/finn_design_Thresholding_Batch_0_0/constraints/Thresholding_Batch_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_Thresholding_Batch_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /tmp/FINN_build_mlp27k_w4a8_ft_clean/vivado_stitch_proj_8ba8a6h2/finn_vivado_stitch_proj.srcs/sources_1/bd/finn_design/ip/finn_design_Thresholding_Batch_0_0/finn_design_Thresholding_Batch_0_0.xci
# IP: The module: 'finn_design_Thresholding_Batch_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/FINN_build_mlp27k_w4a8_ft_clean/vivado_stitch_proj_8ba8a6h2/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/ip/finn_design_Thresholding_Batch_0_0/constraints/Thresholding_Batch_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_Thresholding_Batch_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
