-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
-- Version: 2022.2.2
-- Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FMPadding_Batch_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in0_V_TVALID : IN STD_LOGIC;
    out_V_TREADY : IN STD_LOGIC;
    in0_V_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    in0_V_TREADY : OUT STD_LOGIC;
    out_V_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    out_V_TVALID : OUT STD_LOGIC );
end;


architecture behav of FMPadding_Batch_1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "FMPadding_Batch_1_FMPadding_Batch_1,hls_ip_2022_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.622000,HLS_SYN_LAT=1159,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=94,HLS_SYN_LUT=269,HLS_VERSION=2022_2_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv11_484 : STD_LOGIC_VECTOR (10 downto 0) := "10010000100";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal icmp_ln277_fu_138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge14_i_i_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op46_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal icmp_ln277_reg_273 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal icmp_ln277_reg_273_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in0_V_TDATA_blk_n : STD_LOGIC;
    signal out_V_TDATA_blk_n : STD_LOGIC;
    signal ap_phi_reg_pp0_iter0_outData_V_1_reg_85 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_outData_V_1_reg_85 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_60 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_1_fu_231_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_load : STD_LOGIC_VECTOR (5 downto 0);
    signal y_fu_64 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln277_2_fu_199_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_y_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten_fu_68 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln277_fu_144_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (10 downto 0);
    signal cmp9_not_i_i_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10_not_i_i_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln278_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln277_1_fu_167_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal cmp9_not_i_i_mid1_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10_not_i_i_mid1_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_mid1_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln277_fu_159_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal cmp12_not_i_i_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp14_not_i_i_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln277_1_fu_191_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter2_fsm_state3_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal regslice_both_in0_V_U_apdone_blk : STD_LOGIC;
    signal in0_V_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal in0_V_TVALID_int_regslice : STD_LOGIC;
    signal in0_V_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in0_V_U_ack_in : STD_LOGIC;
    signal out_V_TVALID_int_regslice : STD_LOGIC;
    signal out_V_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_V_U_vld_out : STD_LOGIC;
    signal ap_condition_303 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component FMPadding_Batch_1_flow_control_loop_pipe_no_ap_cont IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;


    component FMPadding_Batch_1_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_no_ap_cont_U : component FMPadding_Batch_1_flow_control_loop_pipe_no_ap_cont
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_const_logic_1,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_const_logic_0,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_const_logic_0);

    regslice_both_in0_V_U : component FMPadding_Batch_1_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_V_TDATA,
        vld_in => in0_V_TVALID,
        ack_in => regslice_both_in0_V_U_ack_in,
        data_out => in0_V_TDATA_int_regslice,
        vld_out => in0_V_TVALID_int_regslice,
        ack_out => in0_V_TREADY_int_regslice,
        apdone_blk => regslice_both_in0_V_U_apdone_blk);

    regslice_both_out_V_U : component FMPadding_Batch_1_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_phi_reg_pp0_iter1_outData_V_1_reg_85,
        vld_in => out_V_TVALID_int_regslice,
        ack_in => out_V_TREADY_int_regslice,
        data_out => out_V_TDATA,
        vld_out => regslice_both_out_V_U_vld_out,
        ack_out => out_V_TREADY,
        apdone_blk => regslice_both_out_V_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_outData_V_1_reg_85_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_303)) then
                if (((brmerge14_i_i_fu_225_p2 = ap_const_lv1_1) and (icmp_ln277_fu_138_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_outData_V_1_reg_85 <= ap_const_lv64_0;
                elsif (((brmerge14_i_i_fu_225_p2 = ap_const_lv1_0) and (icmp_ln277_fu_138_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_outData_V_1_reg_85 <= in0_V_TDATA_int_regslice;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_outData_V_1_reg_85 <= ap_phi_reg_pp0_iter0_outData_V_1_reg_85;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_303)) then
                if ((icmp_ln277_fu_138_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_68 <= add_ln277_fu_144_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_68 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_303)) then
                if ((icmp_ln277_fu_138_p2 = ap_const_lv1_0)) then 
                    x_fu_60 <= x_1_fu_231_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_60 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_303)) then
                if ((icmp_ln277_fu_138_p2 = ap_const_lv1_0)) then 
                    y_fu_64 <= select_ln277_2_fu_199_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_64 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                icmp_ln277_reg_273 <= icmp_ln277_fu_138_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                icmp_ln277_reg_273_pp0_iter1_reg <= icmp_ln277_reg_273;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_predicate_op46_read_state1, icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, in0_V_TVALID_int_regslice, out_V_TREADY_int_regslice)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_predicate_op46_read_state1, ap_CS_iter1_fsm, icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, in0_V_TVALID_int_regslice, out_V_TREADY_int_regslice)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and not(((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not((((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_CS_iter2_fsm, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, out_V_TREADY_int_regslice)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and not(((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                elsif ((not(((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and ((ap_const_logic_0 = ap_CS_iter1_fsm_state2) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0))))))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                elsif ((not(((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then
                    ap_NS_iter2_fsm <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_ST_iter0_fsm_state1),2));
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;
    add_ln277_1_fu_167_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_y_1) + unsigned(ap_const_lv6_1));
    add_ln277_fu_144_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv11_1));
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_predicate_op46_read_state1, in0_V_TVALID_int_regslice)
    begin
        if (((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0))) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state2_blk_assign_proc : process(icmp_ln277_reg_273, ap_block_state2_io, out_V_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) then 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter2_fsm_state3_blk_assign_proc : process(icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, out_V_TREADY_int_regslice)
    begin
        if (((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) then 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_predicate_op46_read_state1, in0_V_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_io_assign_proc : process(icmp_ln277_reg_273, out_V_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(icmp_ln277_reg_273, out_V_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(icmp_ln277_reg_273_pp0_iter1_reg, out_V_TREADY_int_regslice)
    begin
                ap_block_state3_io <= ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, out_V_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_condition_303_assign_proc : process(ap_CS_iter0_fsm_state1, ap_predicate_op46_read_state1, icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, in0_V_TVALID_int_regslice, out_V_TREADY_int_regslice)
    begin
                ap_condition_303 <= (not((((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_iter0_fsm_state1, icmp_ln277_fu_138_p2, ap_predicate_op46_read_state1, icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, in0_V_TVALID_int_regslice, out_V_TREADY_int_regslice)
    begin
        if ((not((((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (icmp_ln277_fu_138_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_outData_V_1_reg_85 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op46_read_state1_assign_proc : process(icmp_ln277_fu_138_p2, brmerge14_i_i_fu_225_p2)
    begin
                ap_predicate_op46_read_state1 <= ((brmerge14_i_i_fu_225_p2 = ap_const_lv1_0) and (icmp_ln277_fu_138_p2 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_iter0_fsm_state1, ap_predicate_op46_read_state1, icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, in0_V_TVALID_int_regslice, out_V_TREADY_int_regslice)
    begin
        if ((not((((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_iter0_fsm_state1, ap_loop_init, indvar_flatten_fu_68)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_x_load_assign_proc : process(ap_CS_iter0_fsm_state1, x_fu_60, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_x_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_x_load <= x_fu_60;
        end if; 
    end process;


    ap_sig_allocacmp_y_1_assign_proc : process(ap_CS_iter0_fsm_state1, ap_loop_init, y_fu_64)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_y_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_y_1 <= y_fu_64;
        end if; 
    end process;

    brmerge14_i_i_fu_225_p2 <= (tmp1_fu_219_p2 or select_ln277_1_fu_191_p3);
    cmp10_not_i_i_fu_126_p2 <= "1" when (unsigned(ap_sig_allocacmp_y_1) > unsigned(ap_const_lv6_20)) else "0";
    cmp10_not_i_i_mid1_fu_179_p2 <= "1" when (unsigned(add_ln277_1_fu_167_p2) > unsigned(ap_const_lv6_20)) else "0";
    cmp12_not_i_i_fu_207_p2 <= "1" when (select_ln277_fu_159_p3 = ap_const_lv6_0) else "0";
    cmp14_not_i_i_fu_213_p2 <= "1" when (unsigned(select_ln277_fu_159_p3) > unsigned(ap_const_lv6_20)) else "0";
    cmp9_not_i_i_fu_120_p2 <= "1" when (ap_sig_allocacmp_y_1 = ap_const_lv6_0) else "0";
    cmp9_not_i_i_mid1_fu_173_p2 <= "1" when (add_ln277_1_fu_167_p2 = ap_const_lv6_0) else "0";
    icmp_ln277_fu_138_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv11_484) else "0";
    icmp_ln278_fu_153_p2 <= "1" when (ap_sig_allocacmp_x_load = ap_const_lv6_22) else "0";

    in0_V_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, ap_predicate_op46_read_state1, in0_V_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op46_read_state1 = ap_const_boolean_1))) then 
            in0_V_TDATA_blk_n <= in0_V_TVALID_int_regslice;
        else 
            in0_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in0_V_TREADY <= regslice_both_in0_V_U_ack_in;

    in0_V_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_predicate_op46_read_state1, icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, in0_V_TVALID_int_regslice, out_V_TREADY_int_regslice)
    begin
        if ((not((((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_predicate_op46_read_state1 = ap_const_boolean_1) and (in0_V_TVALID_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op46_read_state1 = ap_const_boolean_1))) then 
            in0_V_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in0_V_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    out_V_TDATA_blk_n_assign_proc : process(icmp_ln277_reg_273, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, ap_CS_iter2_fsm_state3, out_V_TREADY_int_regslice)
    begin
        if ((((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) then 
            out_V_TDATA_blk_n <= out_V_TREADY_int_regslice;
        else 
            out_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_TVALID <= regslice_both_out_V_U_vld_out;

    out_V_TVALID_int_regslice_assign_proc : process(icmp_ln277_reg_273, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln277_reg_273_pp0_iter1_reg, regslice_both_out_V_U_apdone_blk, ap_block_state3_io, ap_CS_iter2_fsm_state3, out_V_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((regslice_both_out_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln277_reg_273_pp0_iter1_reg = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) or ((icmp_ln277_reg_273 = ap_const_lv1_0) and (out_V_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln277_reg_273 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            out_V_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_V_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln277_1_fu_191_p3 <= 
        tmp_mid1_fu_185_p2 when (icmp_ln278_fu_153_p2(0) = '1') else 
        tmp_fu_132_p2;
    select_ln277_2_fu_199_p3 <= 
        add_ln277_1_fu_167_p2 when (icmp_ln278_fu_153_p2(0) = '1') else 
        ap_sig_allocacmp_y_1;
    select_ln277_fu_159_p3 <= 
        ap_const_lv6_0 when (icmp_ln278_fu_153_p2(0) = '1') else 
        ap_sig_allocacmp_x_load;
    tmp1_fu_219_p2 <= (cmp14_not_i_i_fu_213_p2 or cmp12_not_i_i_fu_207_p2);
    tmp_fu_132_p2 <= (cmp9_not_i_i_fu_120_p2 or cmp10_not_i_i_fu_126_p2);
    tmp_mid1_fu_185_p2 <= (cmp9_not_i_i_mid1_fu_173_p2 or cmp10_not_i_i_mid1_fu_179_p2);
    x_1_fu_231_p2 <= std_logic_vector(unsigned(select_ln277_fu_159_p3) + unsigned(ap_const_lv6_1));
end behav;
