// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_Batch_1_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        buf_V_31_load_1,
        buf_V_30_load_1,
        buf_V_29_load_1,
        buf_V_28_load_1,
        buf_V_27_load_1,
        buf_V_26_load_1,
        buf_V_25_load_1,
        buf_V_24_load_1,
        buf_V_23_load_1,
        buf_V_22_load_1,
        buf_V_21_load_1,
        buf_V_20_load_1,
        buf_V_19_load_1,
        buf_V_18_load_1,
        buf_V_17_load_1,
        buf_V_16_load_1,
        buf_V_15_load_1,
        buf_V_14_load_1,
        buf_V_13_load_1,
        buf_V_12_load_1,
        buf_V_11_load_1,
        buf_V_10_load_1,
        buf_V_9_load_1,
        buf_V_8_load_1,
        buf_V_7_load_1,
        buf_V_6_load_1,
        buf_V_5_load_1,
        buf_V_4_load_1,
        buf_V_3_load_1,
        buf_V_2_load_1,
        buf_V_1_load_1,
        buf_V_load_1,
        buf_V_31_address0,
        buf_V_31_ce0,
        buf_V_31_we0,
        buf_V_31_d0,
        zext_ln156,
        buf_V_30_address0,
        buf_V_30_ce0,
        buf_V_30_we0,
        buf_V_30_d0,
        buf_V_29_address0,
        buf_V_29_ce0,
        buf_V_29_we0,
        buf_V_29_d0,
        buf_V_28_address0,
        buf_V_28_ce0,
        buf_V_28_we0,
        buf_V_28_d0,
        buf_V_27_address0,
        buf_V_27_ce0,
        buf_V_27_we0,
        buf_V_27_d0,
        buf_V_26_address0,
        buf_V_26_ce0,
        buf_V_26_we0,
        buf_V_26_d0,
        buf_V_25_address0,
        buf_V_25_ce0,
        buf_V_25_we0,
        buf_V_25_d0,
        buf_V_24_address0,
        buf_V_24_ce0,
        buf_V_24_we0,
        buf_V_24_d0,
        buf_V_23_address0,
        buf_V_23_ce0,
        buf_V_23_we0,
        buf_V_23_d0,
        buf_V_22_address0,
        buf_V_22_ce0,
        buf_V_22_we0,
        buf_V_22_d0,
        buf_V_21_address0,
        buf_V_21_ce0,
        buf_V_21_we0,
        buf_V_21_d0,
        buf_V_20_address0,
        buf_V_20_ce0,
        buf_V_20_we0,
        buf_V_20_d0,
        buf_V_19_address0,
        buf_V_19_ce0,
        buf_V_19_we0,
        buf_V_19_d0,
        buf_V_18_address0,
        buf_V_18_ce0,
        buf_V_18_we0,
        buf_V_18_d0,
        buf_V_17_address0,
        buf_V_17_ce0,
        buf_V_17_we0,
        buf_V_17_d0,
        buf_V_16_address0,
        buf_V_16_ce0,
        buf_V_16_we0,
        buf_V_16_d0,
        buf_V_15_address0,
        buf_V_15_ce0,
        buf_V_15_we0,
        buf_V_15_d0,
        buf_V_14_address0,
        buf_V_14_ce0,
        buf_V_14_we0,
        buf_V_14_d0,
        buf_V_13_address0,
        buf_V_13_ce0,
        buf_V_13_we0,
        buf_V_13_d0,
        buf_V_12_address0,
        buf_V_12_ce0,
        buf_V_12_we0,
        buf_V_12_d0,
        buf_V_11_address0,
        buf_V_11_ce0,
        buf_V_11_we0,
        buf_V_11_d0,
        buf_V_10_address0,
        buf_V_10_ce0,
        buf_V_10_we0,
        buf_V_10_d0,
        buf_V_9_address0,
        buf_V_9_ce0,
        buf_V_9_we0,
        buf_V_9_d0,
        buf_V_8_address0,
        buf_V_8_ce0,
        buf_V_8_we0,
        buf_V_8_d0,
        buf_V_7_address0,
        buf_V_7_ce0,
        buf_V_7_we0,
        buf_V_7_d0,
        buf_V_6_address0,
        buf_V_6_ce0,
        buf_V_6_we0,
        buf_V_6_d0,
        buf_V_5_address0,
        buf_V_5_ce0,
        buf_V_5_we0,
        buf_V_5_d0,
        buf_V_4_address0,
        buf_V_4_ce0,
        buf_V_4_we0,
        buf_V_4_d0,
        buf_V_3_address0,
        buf_V_3_ce0,
        buf_V_3_we0,
        buf_V_3_d0,
        buf_V_2_address0,
        buf_V_2_ce0,
        buf_V_2_we0,
        buf_V_2_d0,
        buf_V_1_address0,
        buf_V_1_ce0,
        buf_V_1_we0,
        buf_V_1_d0,
        buf_V_address0,
        buf_V_ce0,
        buf_V_we0,
        buf_V_d0,
        in0_V_TDATA,
        in0_V_TREADY
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input  [3:0] buf_V_31_load_1;
input  [3:0] buf_V_30_load_1;
input  [3:0] buf_V_29_load_1;
input  [3:0] buf_V_28_load_1;
input  [3:0] buf_V_27_load_1;
input  [3:0] buf_V_26_load_1;
input  [3:0] buf_V_25_load_1;
input  [3:0] buf_V_24_load_1;
input  [3:0] buf_V_23_load_1;
input  [3:0] buf_V_22_load_1;
input  [3:0] buf_V_21_load_1;
input  [3:0] buf_V_20_load_1;
input  [3:0] buf_V_19_load_1;
input  [3:0] buf_V_18_load_1;
input  [3:0] buf_V_17_load_1;
input  [3:0] buf_V_16_load_1;
input  [3:0] buf_V_15_load_1;
input  [3:0] buf_V_14_load_1;
input  [3:0] buf_V_13_load_1;
input  [3:0] buf_V_12_load_1;
input  [3:0] buf_V_11_load_1;
input  [3:0] buf_V_10_load_1;
input  [3:0] buf_V_9_load_1;
input  [3:0] buf_V_8_load_1;
input  [3:0] buf_V_7_load_1;
input  [3:0] buf_V_6_load_1;
input  [3:0] buf_V_5_load_1;
input  [3:0] buf_V_4_load_1;
input  [3:0] buf_V_3_load_1;
input  [3:0] buf_V_2_load_1;
input  [3:0] buf_V_1_load_1;
input  [3:0] buf_V_load_1;
output  [3:0] buf_V_31_address0;
output   buf_V_31_ce0;
output   buf_V_31_we0;
output  [3:0] buf_V_31_d0;
input  [3:0] zext_ln156;
output  [3:0] buf_V_30_address0;
output   buf_V_30_ce0;
output   buf_V_30_we0;
output  [3:0] buf_V_30_d0;
output  [3:0] buf_V_29_address0;
output   buf_V_29_ce0;
output   buf_V_29_we0;
output  [3:0] buf_V_29_d0;
output  [3:0] buf_V_28_address0;
output   buf_V_28_ce0;
output   buf_V_28_we0;
output  [3:0] buf_V_28_d0;
output  [3:0] buf_V_27_address0;
output   buf_V_27_ce0;
output   buf_V_27_we0;
output  [3:0] buf_V_27_d0;
output  [3:0] buf_V_26_address0;
output   buf_V_26_ce0;
output   buf_V_26_we0;
output  [3:0] buf_V_26_d0;
output  [3:0] buf_V_25_address0;
output   buf_V_25_ce0;
output   buf_V_25_we0;
output  [3:0] buf_V_25_d0;
output  [3:0] buf_V_24_address0;
output   buf_V_24_ce0;
output   buf_V_24_we0;
output  [3:0] buf_V_24_d0;
output  [3:0] buf_V_23_address0;
output   buf_V_23_ce0;
output   buf_V_23_we0;
output  [3:0] buf_V_23_d0;
output  [3:0] buf_V_22_address0;
output   buf_V_22_ce0;
output   buf_V_22_we0;
output  [3:0] buf_V_22_d0;
output  [3:0] buf_V_21_address0;
output   buf_V_21_ce0;
output   buf_V_21_we0;
output  [3:0] buf_V_21_d0;
output  [3:0] buf_V_20_address0;
output   buf_V_20_ce0;
output   buf_V_20_we0;
output  [3:0] buf_V_20_d0;
output  [3:0] buf_V_19_address0;
output   buf_V_19_ce0;
output   buf_V_19_we0;
output  [3:0] buf_V_19_d0;
output  [3:0] buf_V_18_address0;
output   buf_V_18_ce0;
output   buf_V_18_we0;
output  [3:0] buf_V_18_d0;
output  [3:0] buf_V_17_address0;
output   buf_V_17_ce0;
output   buf_V_17_we0;
output  [3:0] buf_V_17_d0;
output  [3:0] buf_V_16_address0;
output   buf_V_16_ce0;
output   buf_V_16_we0;
output  [3:0] buf_V_16_d0;
output  [3:0] buf_V_15_address0;
output   buf_V_15_ce0;
output   buf_V_15_we0;
output  [3:0] buf_V_15_d0;
output  [3:0] buf_V_14_address0;
output   buf_V_14_ce0;
output   buf_V_14_we0;
output  [3:0] buf_V_14_d0;
output  [3:0] buf_V_13_address0;
output   buf_V_13_ce0;
output   buf_V_13_we0;
output  [3:0] buf_V_13_d0;
output  [3:0] buf_V_12_address0;
output   buf_V_12_ce0;
output   buf_V_12_we0;
output  [3:0] buf_V_12_d0;
output  [3:0] buf_V_11_address0;
output   buf_V_11_ce0;
output   buf_V_11_we0;
output  [3:0] buf_V_11_d0;
output  [3:0] buf_V_10_address0;
output   buf_V_10_ce0;
output   buf_V_10_we0;
output  [3:0] buf_V_10_d0;
output  [3:0] buf_V_9_address0;
output   buf_V_9_ce0;
output   buf_V_9_we0;
output  [3:0] buf_V_9_d0;
output  [3:0] buf_V_8_address0;
output   buf_V_8_ce0;
output   buf_V_8_we0;
output  [3:0] buf_V_8_d0;
output  [3:0] buf_V_7_address0;
output   buf_V_7_ce0;
output   buf_V_7_we0;
output  [3:0] buf_V_7_d0;
output  [3:0] buf_V_6_address0;
output   buf_V_6_ce0;
output   buf_V_6_we0;
output  [3:0] buf_V_6_d0;
output  [3:0] buf_V_5_address0;
output   buf_V_5_ce0;
output   buf_V_5_we0;
output  [3:0] buf_V_5_d0;
output  [3:0] buf_V_4_address0;
output   buf_V_4_ce0;
output   buf_V_4_we0;
output  [3:0] buf_V_4_d0;
output  [3:0] buf_V_3_address0;
output   buf_V_3_ce0;
output   buf_V_3_we0;
output  [3:0] buf_V_3_d0;
output  [3:0] buf_V_2_address0;
output   buf_V_2_ce0;
output   buf_V_2_we0;
output  [3:0] buf_V_2_d0;
output  [3:0] buf_V_1_address0;
output   buf_V_1_ce0;
output   buf_V_1_we0;
output  [3:0] buf_V_1_d0;
output  [3:0] buf_V_address0;
output   buf_V_ce0;
output   buf_V_we0;
output  [3:0] buf_V_d0;
input  [127:0] in0_V_TDATA;
output   in0_V_TREADY;

reg ap_idle;
reg buf_V_31_ce0;
reg buf_V_31_we0;
reg buf_V_30_ce0;
reg buf_V_30_we0;
reg buf_V_29_ce0;
reg buf_V_29_we0;
reg buf_V_28_ce0;
reg buf_V_28_we0;
reg buf_V_27_ce0;
reg buf_V_27_we0;
reg buf_V_26_ce0;
reg buf_V_26_we0;
reg buf_V_25_ce0;
reg buf_V_25_we0;
reg buf_V_24_ce0;
reg buf_V_24_we0;
reg buf_V_23_ce0;
reg buf_V_23_we0;
reg buf_V_22_ce0;
reg buf_V_22_we0;
reg buf_V_21_ce0;
reg buf_V_21_we0;
reg buf_V_20_ce0;
reg buf_V_20_we0;
reg buf_V_19_ce0;
reg buf_V_19_we0;
reg buf_V_18_ce0;
reg buf_V_18_we0;
reg buf_V_17_ce0;
reg buf_V_17_we0;
reg buf_V_16_ce0;
reg buf_V_16_we0;
reg buf_V_15_ce0;
reg buf_V_15_we0;
reg buf_V_14_ce0;
reg buf_V_14_we0;
reg buf_V_13_ce0;
reg buf_V_13_we0;
reg buf_V_12_ce0;
reg buf_V_12_we0;
reg buf_V_11_ce0;
reg buf_V_11_we0;
reg buf_V_10_ce0;
reg buf_V_10_we0;
reg buf_V_9_ce0;
reg buf_V_9_we0;
reg buf_V_8_ce0;
reg buf_V_8_we0;
reg buf_V_7_ce0;
reg buf_V_7_we0;
reg buf_V_6_ce0;
reg buf_V_6_we0;
reg buf_V_5_ce0;
reg buf_V_5_we0;
reg buf_V_4_ce0;
reg buf_V_4_we0;
reg buf_V_3_ce0;
reg buf_V_3_we0;
reg buf_V_2_ce0;
reg buf_V_2_we0;
reg buf_V_1_ce0;
reg buf_V_1_we0;
reg buf_V_ce0;
reg buf_V_we0;
reg in0_V_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln158_fu_1252_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
wire   [63:0] zext_ln156_cast_fu_1048_p1;
reg   [1:0] kx_fu_296;
wire   [1:0] kx_2_fu_1258_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_kx_1;
reg   [3:0] oldMax_V_fu_300;
wire   [3:0] select_ln167_fu_1370_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_load;
reg   [3:0] oldMax_V_1_fu_304;
wire   [3:0] select_ln167_1_fu_1395_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_1_load;
reg   [3:0] oldMax_V_2_fu_308;
wire   [3:0] select_ln167_2_fu_1420_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_2_load;
reg   [3:0] oldMax_V_3_fu_312;
wire   [3:0] select_ln167_3_fu_1445_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_3_load;
reg   [3:0] oldMax_V_4_fu_316;
wire   [3:0] select_ln167_4_fu_1470_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_4_load;
reg   [3:0] oldMax_V_5_fu_320;
wire   [3:0] select_ln167_5_fu_1495_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_5_load;
reg   [3:0] oldMax_V_6_fu_324;
wire   [3:0] select_ln167_6_fu_1520_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_6_load;
reg   [3:0] oldMax_V_7_fu_328;
wire   [3:0] select_ln167_7_fu_1545_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_7_load;
reg   [3:0] oldMax_V_8_fu_332;
wire   [3:0] select_ln167_8_fu_1570_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_8_load;
reg   [3:0] oldMax_V_9_fu_336;
wire   [3:0] select_ln167_9_fu_1595_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_9_load;
reg   [3:0] oldMax_V_10_fu_340;
wire   [3:0] select_ln167_10_fu_1620_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_10_load;
reg   [3:0] oldMax_V_11_fu_344;
wire   [3:0] select_ln167_11_fu_1645_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_11_load;
reg   [3:0] oldMax_V_12_fu_348;
wire   [3:0] select_ln167_12_fu_1670_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_12_load;
reg   [3:0] oldMax_V_13_fu_352;
wire   [3:0] select_ln167_13_fu_1695_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_13_load;
reg   [3:0] oldMax_V_14_fu_356;
wire   [3:0] select_ln167_14_fu_1720_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_14_load;
reg   [3:0] oldMax_V_15_fu_360;
wire   [3:0] select_ln167_15_fu_1745_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_15_load;
reg   [3:0] oldMax_V_16_fu_364;
wire   [3:0] select_ln167_16_fu_1770_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_16_load;
reg   [3:0] oldMax_V_17_fu_368;
wire   [3:0] select_ln167_17_fu_1795_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_17_load;
reg   [3:0] oldMax_V_18_fu_372;
wire   [3:0] select_ln167_18_fu_1820_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_18_load;
reg   [3:0] oldMax_V_19_fu_376;
wire   [3:0] select_ln167_19_fu_1845_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_19_load;
reg   [3:0] oldMax_V_20_fu_380;
wire   [3:0] select_ln167_20_fu_1870_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_20_load;
reg   [3:0] oldMax_V_21_fu_384;
wire   [3:0] select_ln167_21_fu_1895_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_21_load;
reg   [3:0] oldMax_V_22_fu_388;
wire   [3:0] select_ln167_22_fu_1920_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_22_load;
reg   [3:0] oldMax_V_23_fu_392;
wire   [3:0] select_ln167_23_fu_1945_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_23_load;
reg   [3:0] oldMax_V_24_fu_396;
wire   [3:0] select_ln167_24_fu_1970_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_24_load;
reg   [3:0] oldMax_V_25_fu_400;
wire   [3:0] select_ln167_25_fu_1995_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_25_load;
reg   [3:0] oldMax_V_26_fu_404;
wire   [3:0] select_ln167_26_fu_2020_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_26_load;
reg   [3:0] oldMax_V_27_fu_408;
wire   [3:0] select_ln167_27_fu_2045_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_27_load;
reg   [3:0] oldMax_V_28_fu_412;
wire   [3:0] select_ln167_28_fu_2070_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_28_load;
reg   [3:0] oldMax_V_29_fu_416;
wire   [3:0] select_ln167_29_fu_2095_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_29_load;
reg   [3:0] oldMax_V_30_fu_420;
wire   [3:0] select_ln167_30_fu_2120_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_30_load;
reg   [3:0] oldMax_V_31_fu_424;
wire   [3:0] select_ln167_31_fu_2145_p3;
reg   [3:0] ap_sig_allocacmp_oldMax_V_31_load;
wire   [0:0] icmp_ln158_1_fu_2154_p2;
wire   [3:0] channeldata_V_fu_1360_p1;
wire   [0:0] icmp_ln1035_fu_1364_p2;
wire   [3:0] channeldata_V_1_fu_1379_p4;
wire   [0:0] icmp_ln1035_1_fu_1389_p2;
wire   [3:0] channeldata_V_2_fu_1404_p4;
wire   [0:0] icmp_ln1035_2_fu_1414_p2;
wire   [3:0] channeldata_V_3_fu_1429_p4;
wire   [0:0] icmp_ln1035_3_fu_1439_p2;
wire   [3:0] channeldata_V_4_fu_1454_p4;
wire   [0:0] icmp_ln1035_4_fu_1464_p2;
wire   [3:0] channeldata_V_5_fu_1479_p4;
wire   [0:0] icmp_ln1035_5_fu_1489_p2;
wire   [3:0] channeldata_V_6_fu_1504_p4;
wire   [0:0] icmp_ln1035_6_fu_1514_p2;
wire   [3:0] channeldata_V_7_fu_1529_p4;
wire   [0:0] icmp_ln1035_7_fu_1539_p2;
wire   [3:0] channeldata_V_8_fu_1554_p4;
wire   [0:0] icmp_ln1035_8_fu_1564_p2;
wire   [3:0] channeldata_V_9_fu_1579_p4;
wire   [0:0] icmp_ln1035_9_fu_1589_p2;
wire   [3:0] channeldata_V_10_fu_1604_p4;
wire   [0:0] icmp_ln1035_10_fu_1614_p2;
wire   [3:0] channeldata_V_11_fu_1629_p4;
wire   [0:0] icmp_ln1035_11_fu_1639_p2;
wire   [3:0] channeldata_V_12_fu_1654_p4;
wire   [0:0] icmp_ln1035_12_fu_1664_p2;
wire   [3:0] channeldata_V_13_fu_1679_p4;
wire   [0:0] icmp_ln1035_13_fu_1689_p2;
wire   [3:0] channeldata_V_14_fu_1704_p4;
wire   [0:0] icmp_ln1035_14_fu_1714_p2;
wire   [3:0] channeldata_V_15_fu_1729_p4;
wire   [0:0] icmp_ln1035_15_fu_1739_p2;
wire   [3:0] channeldata_V_16_fu_1754_p4;
wire   [0:0] icmp_ln1035_16_fu_1764_p2;
wire   [3:0] channeldata_V_17_fu_1779_p4;
wire   [0:0] icmp_ln1035_17_fu_1789_p2;
wire   [3:0] channeldata_V_18_fu_1804_p4;
wire   [0:0] icmp_ln1035_18_fu_1814_p2;
wire   [3:0] channeldata_V_19_fu_1829_p4;
wire   [0:0] icmp_ln1035_19_fu_1839_p2;
wire   [3:0] channeldata_V_20_fu_1854_p4;
wire   [0:0] icmp_ln1035_20_fu_1864_p2;
wire   [3:0] channeldata_V_21_fu_1879_p4;
wire   [0:0] icmp_ln1035_21_fu_1889_p2;
wire   [3:0] channeldata_V_22_fu_1904_p4;
wire   [0:0] icmp_ln1035_22_fu_1914_p2;
wire   [3:0] channeldata_V_23_fu_1929_p4;
wire   [0:0] icmp_ln1035_23_fu_1939_p2;
wire   [3:0] channeldata_V_24_fu_1954_p4;
wire   [0:0] icmp_ln1035_24_fu_1964_p2;
wire   [3:0] channeldata_V_25_fu_1979_p4;
wire   [0:0] icmp_ln1035_25_fu_1989_p2;
wire   [3:0] channeldata_V_26_fu_2004_p4;
wire   [0:0] icmp_ln1035_26_fu_2014_p2;
wire   [3:0] channeldata_V_27_fu_2029_p4;
wire   [0:0] icmp_ln1035_27_fu_2039_p2;
wire   [3:0] channeldata_V_28_fu_2054_p4;
wire   [0:0] icmp_ln1035_28_fu_2064_p2;
wire   [3:0] channeldata_V_29_fu_2079_p4;
wire   [0:0] icmp_ln1035_29_fu_2089_p2;
wire   [3:0] channeldata_V_30_fu_2104_p4;
wire   [0:0] icmp_ln1035_30_fu_2114_p2;
wire   [3:0] channeldata_V_31_fu_2129_p4;
wire   [0:0] icmp_ln1035_31_fu_2139_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_1053;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

StreamingMaxPool_Batch_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            kx_fu_296 <= kx_2_fu_1258_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kx_fu_296 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_10_fu_340 <= select_ln167_10_fu_1620_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_10_fu_340 <= buf_V_10_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_11_fu_344 <= select_ln167_11_fu_1645_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_11_fu_344 <= buf_V_11_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_12_fu_348 <= select_ln167_12_fu_1670_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_12_fu_348 <= buf_V_12_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_13_fu_352 <= select_ln167_13_fu_1695_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_13_fu_352 <= buf_V_13_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_14_fu_356 <= select_ln167_14_fu_1720_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_14_fu_356 <= buf_V_14_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_15_fu_360 <= select_ln167_15_fu_1745_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_15_fu_360 <= buf_V_15_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_16_fu_364 <= select_ln167_16_fu_1770_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_16_fu_364 <= buf_V_16_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_17_fu_368 <= select_ln167_17_fu_1795_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_17_fu_368 <= buf_V_17_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_18_fu_372 <= select_ln167_18_fu_1820_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_18_fu_372 <= buf_V_18_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_19_fu_376 <= select_ln167_19_fu_1845_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_19_fu_376 <= buf_V_19_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_1_fu_304 <= select_ln167_1_fu_1395_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_1_fu_304 <= buf_V_1_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_20_fu_380 <= select_ln167_20_fu_1870_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_20_fu_380 <= buf_V_20_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_21_fu_384 <= select_ln167_21_fu_1895_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_21_fu_384 <= buf_V_21_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_22_fu_388 <= select_ln167_22_fu_1920_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_22_fu_388 <= buf_V_22_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_23_fu_392 <= select_ln167_23_fu_1945_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_23_fu_392 <= buf_V_23_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_24_fu_396 <= select_ln167_24_fu_1970_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_24_fu_396 <= buf_V_24_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_25_fu_400 <= select_ln167_25_fu_1995_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_25_fu_400 <= buf_V_25_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_26_fu_404 <= select_ln167_26_fu_2020_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_26_fu_404 <= buf_V_26_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_27_fu_408 <= select_ln167_27_fu_2045_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_27_fu_408 <= buf_V_27_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_28_fu_412 <= select_ln167_28_fu_2070_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_28_fu_412 <= buf_V_28_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_29_fu_416 <= select_ln167_29_fu_2095_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_29_fu_416 <= buf_V_29_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_2_fu_308 <= select_ln167_2_fu_1420_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_2_fu_308 <= buf_V_2_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_30_fu_420 <= select_ln167_30_fu_2120_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_30_fu_420 <= buf_V_30_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_31_fu_424 <= select_ln167_31_fu_2145_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_31_fu_424 <= buf_V_31_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_3_fu_312 <= select_ln167_3_fu_1445_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_3_fu_312 <= buf_V_3_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_4_fu_316 <= select_ln167_4_fu_1470_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_4_fu_316 <= buf_V_4_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_5_fu_320 <= select_ln167_5_fu_1495_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_5_fu_320 <= buf_V_5_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_6_fu_324 <= select_ln167_6_fu_1520_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_6_fu_324 <= buf_V_6_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_7_fu_328 <= select_ln167_7_fu_1545_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_7_fu_328 <= buf_V_7_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_8_fu_332 <= select_ln167_8_fu_1570_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_8_fu_332 <= buf_V_8_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_9_fu_336 <= select_ln167_9_fu_1595_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_9_fu_336 <= buf_V_9_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1053)) begin
        if ((icmp_ln158_fu_1252_p2 == 1'd0)) begin
            oldMax_V_fu_300 <= select_ln167_fu_1370_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_fu_300 <= buf_V_load_1;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_fu_1252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_kx_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_kx_1 = kx_fu_296;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_10_load = buf_V_10_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_10_load = oldMax_V_10_fu_340;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_11_load = buf_V_11_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_11_load = oldMax_V_11_fu_344;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_12_load = buf_V_12_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_12_load = oldMax_V_12_fu_348;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_13_load = buf_V_13_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_13_load = oldMax_V_13_fu_352;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_14_load = buf_V_14_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_14_load = oldMax_V_14_fu_356;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_15_load = buf_V_15_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_15_load = oldMax_V_15_fu_360;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_16_load = buf_V_16_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_16_load = oldMax_V_16_fu_364;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_17_load = buf_V_17_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_17_load = oldMax_V_17_fu_368;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_18_load = buf_V_18_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_18_load = oldMax_V_18_fu_372;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_19_load = buf_V_19_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_19_load = oldMax_V_19_fu_376;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_1_load = buf_V_1_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_1_load = oldMax_V_1_fu_304;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_20_load = buf_V_20_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_20_load = oldMax_V_20_fu_380;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_21_load = buf_V_21_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_21_load = oldMax_V_21_fu_384;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_22_load = buf_V_22_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_22_load = oldMax_V_22_fu_388;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_23_load = buf_V_23_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_23_load = oldMax_V_23_fu_392;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_24_load = buf_V_24_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_24_load = oldMax_V_24_fu_396;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_25_load = buf_V_25_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_25_load = oldMax_V_25_fu_400;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_26_load = buf_V_26_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_26_load = oldMax_V_26_fu_404;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_27_load = buf_V_27_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_27_load = oldMax_V_27_fu_408;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_28_load = buf_V_28_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_28_load = oldMax_V_28_fu_412;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_29_load = buf_V_29_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_29_load = oldMax_V_29_fu_416;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_2_load = buf_V_2_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_2_load = oldMax_V_2_fu_308;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_30_load = buf_V_30_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_30_load = oldMax_V_30_fu_420;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_31_load = buf_V_31_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_31_load = oldMax_V_31_fu_424;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_3_load = buf_V_3_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_3_load = oldMax_V_3_fu_312;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_4_load = buf_V_4_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_4_load = oldMax_V_4_fu_316;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_5_load = buf_V_5_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_5_load = oldMax_V_5_fu_320;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_6_load = buf_V_6_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_6_load = oldMax_V_6_fu_324;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_7_load = buf_V_7_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_7_load = oldMax_V_7_fu_328;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_8_load = buf_V_8_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_8_load = oldMax_V_8_fu_332;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_9_load = buf_V_9_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_9_load = oldMax_V_9_fu_336;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oldMax_V_load = buf_V_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_load = oldMax_V_fu_300;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_10_ce0 = 1'b1;
    end else begin
        buf_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_10_we0 = 1'b1;
    end else begin
        buf_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_11_ce0 = 1'b1;
    end else begin
        buf_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_11_we0 = 1'b1;
    end else begin
        buf_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_12_ce0 = 1'b1;
    end else begin
        buf_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_12_we0 = 1'b1;
    end else begin
        buf_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_13_ce0 = 1'b1;
    end else begin
        buf_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_13_we0 = 1'b1;
    end else begin
        buf_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_14_ce0 = 1'b1;
    end else begin
        buf_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_14_we0 = 1'b1;
    end else begin
        buf_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_15_ce0 = 1'b1;
    end else begin
        buf_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_15_we0 = 1'b1;
    end else begin
        buf_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_16_ce0 = 1'b1;
    end else begin
        buf_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_16_we0 = 1'b1;
    end else begin
        buf_V_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_17_ce0 = 1'b1;
    end else begin
        buf_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_17_we0 = 1'b1;
    end else begin
        buf_V_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_18_ce0 = 1'b1;
    end else begin
        buf_V_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_18_we0 = 1'b1;
    end else begin
        buf_V_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_19_ce0 = 1'b1;
    end else begin
        buf_V_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_19_we0 = 1'b1;
    end else begin
        buf_V_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_1_we0 = 1'b1;
    end else begin
        buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_20_ce0 = 1'b1;
    end else begin
        buf_V_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_20_we0 = 1'b1;
    end else begin
        buf_V_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_21_ce0 = 1'b1;
    end else begin
        buf_V_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_21_we0 = 1'b1;
    end else begin
        buf_V_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_22_ce0 = 1'b1;
    end else begin
        buf_V_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_22_we0 = 1'b1;
    end else begin
        buf_V_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_23_ce0 = 1'b1;
    end else begin
        buf_V_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_23_we0 = 1'b1;
    end else begin
        buf_V_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_24_ce0 = 1'b1;
    end else begin
        buf_V_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_24_we0 = 1'b1;
    end else begin
        buf_V_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_25_ce0 = 1'b1;
    end else begin
        buf_V_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_25_we0 = 1'b1;
    end else begin
        buf_V_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_26_ce0 = 1'b1;
    end else begin
        buf_V_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_26_we0 = 1'b1;
    end else begin
        buf_V_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_27_ce0 = 1'b1;
    end else begin
        buf_V_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_27_we0 = 1'b1;
    end else begin
        buf_V_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_28_ce0 = 1'b1;
    end else begin
        buf_V_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_28_we0 = 1'b1;
    end else begin
        buf_V_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_29_ce0 = 1'b1;
    end else begin
        buf_V_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_29_we0 = 1'b1;
    end else begin
        buf_V_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_2_we0 = 1'b1;
    end else begin
        buf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_30_ce0 = 1'b1;
    end else begin
        buf_V_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_30_we0 = 1'b1;
    end else begin
        buf_V_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_31_ce0 = 1'b1;
    end else begin
        buf_V_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_31_we0 = 1'b1;
    end else begin
        buf_V_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_3_ce0 = 1'b1;
    end else begin
        buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_3_we0 = 1'b1;
    end else begin
        buf_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_4_ce0 = 1'b1;
    end else begin
        buf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_4_we0 = 1'b1;
    end else begin
        buf_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_5_ce0 = 1'b1;
    end else begin
        buf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_5_we0 = 1'b1;
    end else begin
        buf_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_6_ce0 = 1'b1;
    end else begin
        buf_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_6_we0 = 1'b1;
    end else begin
        buf_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_7_ce0 = 1'b1;
    end else begin
        buf_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_7_we0 = 1'b1;
    end else begin
        buf_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_8_ce0 = 1'b1;
    end else begin
        buf_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_8_we0 = 1'b1;
    end else begin
        buf_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_9_ce0 = 1'b1;
    end else begin
        buf_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_9_we0 = 1'b1;
    end else begin
        buf_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_2154_p2 == 1'd1) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_we0 = 1'b1;
    end else begin
        buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_1053 = (~((ap_start_int == 1'b0) | ((icmp_ln158_fu_1252_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buf_V_10_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_10_d0 = ((icmp_ln1035_10_fu_1614_p2[0:0] == 1'b1) ? channeldata_V_10_fu_1604_p4 : ap_sig_allocacmp_oldMax_V_10_load);

assign buf_V_11_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_11_d0 = ((icmp_ln1035_11_fu_1639_p2[0:0] == 1'b1) ? channeldata_V_11_fu_1629_p4 : ap_sig_allocacmp_oldMax_V_11_load);

assign buf_V_12_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_12_d0 = ((icmp_ln1035_12_fu_1664_p2[0:0] == 1'b1) ? channeldata_V_12_fu_1654_p4 : ap_sig_allocacmp_oldMax_V_12_load);

assign buf_V_13_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_13_d0 = ((icmp_ln1035_13_fu_1689_p2[0:0] == 1'b1) ? channeldata_V_13_fu_1679_p4 : ap_sig_allocacmp_oldMax_V_13_load);

assign buf_V_14_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_14_d0 = ((icmp_ln1035_14_fu_1714_p2[0:0] == 1'b1) ? channeldata_V_14_fu_1704_p4 : ap_sig_allocacmp_oldMax_V_14_load);

assign buf_V_15_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_15_d0 = ((icmp_ln1035_15_fu_1739_p2[0:0] == 1'b1) ? channeldata_V_15_fu_1729_p4 : ap_sig_allocacmp_oldMax_V_15_load);

assign buf_V_16_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_16_d0 = ((icmp_ln1035_16_fu_1764_p2[0:0] == 1'b1) ? channeldata_V_16_fu_1754_p4 : ap_sig_allocacmp_oldMax_V_16_load);

assign buf_V_17_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_17_d0 = ((icmp_ln1035_17_fu_1789_p2[0:0] == 1'b1) ? channeldata_V_17_fu_1779_p4 : ap_sig_allocacmp_oldMax_V_17_load);

assign buf_V_18_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_18_d0 = ((icmp_ln1035_18_fu_1814_p2[0:0] == 1'b1) ? channeldata_V_18_fu_1804_p4 : ap_sig_allocacmp_oldMax_V_18_load);

assign buf_V_19_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_19_d0 = ((icmp_ln1035_19_fu_1839_p2[0:0] == 1'b1) ? channeldata_V_19_fu_1829_p4 : ap_sig_allocacmp_oldMax_V_19_load);

assign buf_V_1_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_1_d0 = ((icmp_ln1035_1_fu_1389_p2[0:0] == 1'b1) ? channeldata_V_1_fu_1379_p4 : ap_sig_allocacmp_oldMax_V_1_load);

assign buf_V_20_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_20_d0 = ((icmp_ln1035_20_fu_1864_p2[0:0] == 1'b1) ? channeldata_V_20_fu_1854_p4 : ap_sig_allocacmp_oldMax_V_20_load);

assign buf_V_21_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_21_d0 = ((icmp_ln1035_21_fu_1889_p2[0:0] == 1'b1) ? channeldata_V_21_fu_1879_p4 : ap_sig_allocacmp_oldMax_V_21_load);

assign buf_V_22_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_22_d0 = ((icmp_ln1035_22_fu_1914_p2[0:0] == 1'b1) ? channeldata_V_22_fu_1904_p4 : ap_sig_allocacmp_oldMax_V_22_load);

assign buf_V_23_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_23_d0 = ((icmp_ln1035_23_fu_1939_p2[0:0] == 1'b1) ? channeldata_V_23_fu_1929_p4 : ap_sig_allocacmp_oldMax_V_23_load);

assign buf_V_24_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_24_d0 = ((icmp_ln1035_24_fu_1964_p2[0:0] == 1'b1) ? channeldata_V_24_fu_1954_p4 : ap_sig_allocacmp_oldMax_V_24_load);

assign buf_V_25_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_25_d0 = ((icmp_ln1035_25_fu_1989_p2[0:0] == 1'b1) ? channeldata_V_25_fu_1979_p4 : ap_sig_allocacmp_oldMax_V_25_load);

assign buf_V_26_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_26_d0 = ((icmp_ln1035_26_fu_2014_p2[0:0] == 1'b1) ? channeldata_V_26_fu_2004_p4 : ap_sig_allocacmp_oldMax_V_26_load);

assign buf_V_27_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_27_d0 = ((icmp_ln1035_27_fu_2039_p2[0:0] == 1'b1) ? channeldata_V_27_fu_2029_p4 : ap_sig_allocacmp_oldMax_V_27_load);

assign buf_V_28_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_28_d0 = ((icmp_ln1035_28_fu_2064_p2[0:0] == 1'b1) ? channeldata_V_28_fu_2054_p4 : ap_sig_allocacmp_oldMax_V_28_load);

assign buf_V_29_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_29_d0 = ((icmp_ln1035_29_fu_2089_p2[0:0] == 1'b1) ? channeldata_V_29_fu_2079_p4 : ap_sig_allocacmp_oldMax_V_29_load);

assign buf_V_2_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_2_d0 = ((icmp_ln1035_2_fu_1414_p2[0:0] == 1'b1) ? channeldata_V_2_fu_1404_p4 : ap_sig_allocacmp_oldMax_V_2_load);

assign buf_V_30_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_30_d0 = ((icmp_ln1035_30_fu_2114_p2[0:0] == 1'b1) ? channeldata_V_30_fu_2104_p4 : ap_sig_allocacmp_oldMax_V_30_load);

assign buf_V_31_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_31_d0 = ((icmp_ln1035_31_fu_2139_p2[0:0] == 1'b1) ? channeldata_V_31_fu_2129_p4 : ap_sig_allocacmp_oldMax_V_31_load);

assign buf_V_3_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_3_d0 = ((icmp_ln1035_3_fu_1439_p2[0:0] == 1'b1) ? channeldata_V_3_fu_1429_p4 : ap_sig_allocacmp_oldMax_V_3_load);

assign buf_V_4_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_4_d0 = ((icmp_ln1035_4_fu_1464_p2[0:0] == 1'b1) ? channeldata_V_4_fu_1454_p4 : ap_sig_allocacmp_oldMax_V_4_load);

assign buf_V_5_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_5_d0 = ((icmp_ln1035_5_fu_1489_p2[0:0] == 1'b1) ? channeldata_V_5_fu_1479_p4 : ap_sig_allocacmp_oldMax_V_5_load);

assign buf_V_6_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_6_d0 = ((icmp_ln1035_6_fu_1514_p2[0:0] == 1'b1) ? channeldata_V_6_fu_1504_p4 : ap_sig_allocacmp_oldMax_V_6_load);

assign buf_V_7_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_7_d0 = ((icmp_ln1035_7_fu_1539_p2[0:0] == 1'b1) ? channeldata_V_7_fu_1529_p4 : ap_sig_allocacmp_oldMax_V_7_load);

assign buf_V_8_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_8_d0 = ((icmp_ln1035_8_fu_1564_p2[0:0] == 1'b1) ? channeldata_V_8_fu_1554_p4 : ap_sig_allocacmp_oldMax_V_8_load);

assign buf_V_9_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_9_d0 = ((icmp_ln1035_9_fu_1589_p2[0:0] == 1'b1) ? channeldata_V_9_fu_1579_p4 : ap_sig_allocacmp_oldMax_V_9_load);

assign buf_V_address0 = zext_ln156_cast_fu_1048_p1;

assign buf_V_d0 = ((icmp_ln1035_fu_1364_p2[0:0] == 1'b1) ? channeldata_V_fu_1360_p1 : ap_sig_allocacmp_oldMax_V_load);

assign channeldata_V_10_fu_1604_p4 = {{in0_V_TDATA[43:40]}};

assign channeldata_V_11_fu_1629_p4 = {{in0_V_TDATA[47:44]}};

assign channeldata_V_12_fu_1654_p4 = {{in0_V_TDATA[51:48]}};

assign channeldata_V_13_fu_1679_p4 = {{in0_V_TDATA[55:52]}};

assign channeldata_V_14_fu_1704_p4 = {{in0_V_TDATA[59:56]}};

assign channeldata_V_15_fu_1729_p4 = {{in0_V_TDATA[63:60]}};

assign channeldata_V_16_fu_1754_p4 = {{in0_V_TDATA[67:64]}};

assign channeldata_V_17_fu_1779_p4 = {{in0_V_TDATA[71:68]}};

assign channeldata_V_18_fu_1804_p4 = {{in0_V_TDATA[75:72]}};

assign channeldata_V_19_fu_1829_p4 = {{in0_V_TDATA[79:76]}};

assign channeldata_V_1_fu_1379_p4 = {{in0_V_TDATA[7:4]}};

assign channeldata_V_20_fu_1854_p4 = {{in0_V_TDATA[83:80]}};

assign channeldata_V_21_fu_1879_p4 = {{in0_V_TDATA[87:84]}};

assign channeldata_V_22_fu_1904_p4 = {{in0_V_TDATA[91:88]}};

assign channeldata_V_23_fu_1929_p4 = {{in0_V_TDATA[95:92]}};

assign channeldata_V_24_fu_1954_p4 = {{in0_V_TDATA[99:96]}};

assign channeldata_V_25_fu_1979_p4 = {{in0_V_TDATA[103:100]}};

assign channeldata_V_26_fu_2004_p4 = {{in0_V_TDATA[107:104]}};

assign channeldata_V_27_fu_2029_p4 = {{in0_V_TDATA[111:108]}};

assign channeldata_V_28_fu_2054_p4 = {{in0_V_TDATA[115:112]}};

assign channeldata_V_29_fu_2079_p4 = {{in0_V_TDATA[119:116]}};

assign channeldata_V_2_fu_1404_p4 = {{in0_V_TDATA[11:8]}};

assign channeldata_V_30_fu_2104_p4 = {{in0_V_TDATA[123:120]}};

assign channeldata_V_31_fu_2129_p4 = {{in0_V_TDATA[127:124]}};

assign channeldata_V_3_fu_1429_p4 = {{in0_V_TDATA[15:12]}};

assign channeldata_V_4_fu_1454_p4 = {{in0_V_TDATA[19:16]}};

assign channeldata_V_5_fu_1479_p4 = {{in0_V_TDATA[23:20]}};

assign channeldata_V_6_fu_1504_p4 = {{in0_V_TDATA[27:24]}};

assign channeldata_V_7_fu_1529_p4 = {{in0_V_TDATA[31:28]}};

assign channeldata_V_8_fu_1554_p4 = {{in0_V_TDATA[35:32]}};

assign channeldata_V_9_fu_1579_p4 = {{in0_V_TDATA[39:36]}};

assign channeldata_V_fu_1360_p1 = in0_V_TDATA[3:0];

assign icmp_ln1035_10_fu_1614_p2 = ((channeldata_V_10_fu_1604_p4 > ap_sig_allocacmp_oldMax_V_10_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_11_fu_1639_p2 = ((channeldata_V_11_fu_1629_p4 > ap_sig_allocacmp_oldMax_V_11_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_12_fu_1664_p2 = ((channeldata_V_12_fu_1654_p4 > ap_sig_allocacmp_oldMax_V_12_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_13_fu_1689_p2 = ((channeldata_V_13_fu_1679_p4 > ap_sig_allocacmp_oldMax_V_13_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_14_fu_1714_p2 = ((channeldata_V_14_fu_1704_p4 > ap_sig_allocacmp_oldMax_V_14_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_15_fu_1739_p2 = ((channeldata_V_15_fu_1729_p4 > ap_sig_allocacmp_oldMax_V_15_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_16_fu_1764_p2 = ((channeldata_V_16_fu_1754_p4 > ap_sig_allocacmp_oldMax_V_16_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_17_fu_1789_p2 = ((channeldata_V_17_fu_1779_p4 > ap_sig_allocacmp_oldMax_V_17_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_18_fu_1814_p2 = ((channeldata_V_18_fu_1804_p4 > ap_sig_allocacmp_oldMax_V_18_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_19_fu_1839_p2 = ((channeldata_V_19_fu_1829_p4 > ap_sig_allocacmp_oldMax_V_19_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_1_fu_1389_p2 = ((channeldata_V_1_fu_1379_p4 > ap_sig_allocacmp_oldMax_V_1_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_20_fu_1864_p2 = ((channeldata_V_20_fu_1854_p4 > ap_sig_allocacmp_oldMax_V_20_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_21_fu_1889_p2 = ((channeldata_V_21_fu_1879_p4 > ap_sig_allocacmp_oldMax_V_21_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_22_fu_1914_p2 = ((channeldata_V_22_fu_1904_p4 > ap_sig_allocacmp_oldMax_V_22_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_23_fu_1939_p2 = ((channeldata_V_23_fu_1929_p4 > ap_sig_allocacmp_oldMax_V_23_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_24_fu_1964_p2 = ((channeldata_V_24_fu_1954_p4 > ap_sig_allocacmp_oldMax_V_24_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_25_fu_1989_p2 = ((channeldata_V_25_fu_1979_p4 > ap_sig_allocacmp_oldMax_V_25_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_26_fu_2014_p2 = ((channeldata_V_26_fu_2004_p4 > ap_sig_allocacmp_oldMax_V_26_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_27_fu_2039_p2 = ((channeldata_V_27_fu_2029_p4 > ap_sig_allocacmp_oldMax_V_27_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_28_fu_2064_p2 = ((channeldata_V_28_fu_2054_p4 > ap_sig_allocacmp_oldMax_V_28_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_29_fu_2089_p2 = ((channeldata_V_29_fu_2079_p4 > ap_sig_allocacmp_oldMax_V_29_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_1414_p2 = ((channeldata_V_2_fu_1404_p4 > ap_sig_allocacmp_oldMax_V_2_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_30_fu_2114_p2 = ((channeldata_V_30_fu_2104_p4 > ap_sig_allocacmp_oldMax_V_30_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_31_fu_2139_p2 = ((channeldata_V_31_fu_2129_p4 > ap_sig_allocacmp_oldMax_V_31_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_3_fu_1439_p2 = ((channeldata_V_3_fu_1429_p4 > ap_sig_allocacmp_oldMax_V_3_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_4_fu_1464_p2 = ((channeldata_V_4_fu_1454_p4 > ap_sig_allocacmp_oldMax_V_4_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_5_fu_1489_p2 = ((channeldata_V_5_fu_1479_p4 > ap_sig_allocacmp_oldMax_V_5_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_6_fu_1514_p2 = ((channeldata_V_6_fu_1504_p4 > ap_sig_allocacmp_oldMax_V_6_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_7_fu_1539_p2 = ((channeldata_V_7_fu_1529_p4 > ap_sig_allocacmp_oldMax_V_7_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_8_fu_1564_p2 = ((channeldata_V_8_fu_1554_p4 > ap_sig_allocacmp_oldMax_V_8_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_9_fu_1589_p2 = ((channeldata_V_9_fu_1579_p4 > ap_sig_allocacmp_oldMax_V_9_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_1364_p2 = ((channeldata_V_fu_1360_p1 > ap_sig_allocacmp_oldMax_V_load) ? 1'b1 : 1'b0);

assign icmp_ln158_1_fu_2154_p2 = ((kx_2_fu_1258_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_1252_p2 = ((ap_sig_allocacmp_kx_1 == 2'd2) ? 1'b1 : 1'b0);

assign kx_2_fu_1258_p2 = (ap_sig_allocacmp_kx_1 + 2'd1);

assign select_ln167_10_fu_1620_p3 = ((icmp_ln1035_10_fu_1614_p2[0:0] == 1'b1) ? channeldata_V_10_fu_1604_p4 : ap_sig_allocacmp_oldMax_V_10_load);

assign select_ln167_11_fu_1645_p3 = ((icmp_ln1035_11_fu_1639_p2[0:0] == 1'b1) ? channeldata_V_11_fu_1629_p4 : ap_sig_allocacmp_oldMax_V_11_load);

assign select_ln167_12_fu_1670_p3 = ((icmp_ln1035_12_fu_1664_p2[0:0] == 1'b1) ? channeldata_V_12_fu_1654_p4 : ap_sig_allocacmp_oldMax_V_12_load);

assign select_ln167_13_fu_1695_p3 = ((icmp_ln1035_13_fu_1689_p2[0:0] == 1'b1) ? channeldata_V_13_fu_1679_p4 : ap_sig_allocacmp_oldMax_V_13_load);

assign select_ln167_14_fu_1720_p3 = ((icmp_ln1035_14_fu_1714_p2[0:0] == 1'b1) ? channeldata_V_14_fu_1704_p4 : ap_sig_allocacmp_oldMax_V_14_load);

assign select_ln167_15_fu_1745_p3 = ((icmp_ln1035_15_fu_1739_p2[0:0] == 1'b1) ? channeldata_V_15_fu_1729_p4 : ap_sig_allocacmp_oldMax_V_15_load);

assign select_ln167_16_fu_1770_p3 = ((icmp_ln1035_16_fu_1764_p2[0:0] == 1'b1) ? channeldata_V_16_fu_1754_p4 : ap_sig_allocacmp_oldMax_V_16_load);

assign select_ln167_17_fu_1795_p3 = ((icmp_ln1035_17_fu_1789_p2[0:0] == 1'b1) ? channeldata_V_17_fu_1779_p4 : ap_sig_allocacmp_oldMax_V_17_load);

assign select_ln167_18_fu_1820_p3 = ((icmp_ln1035_18_fu_1814_p2[0:0] == 1'b1) ? channeldata_V_18_fu_1804_p4 : ap_sig_allocacmp_oldMax_V_18_load);

assign select_ln167_19_fu_1845_p3 = ((icmp_ln1035_19_fu_1839_p2[0:0] == 1'b1) ? channeldata_V_19_fu_1829_p4 : ap_sig_allocacmp_oldMax_V_19_load);

assign select_ln167_1_fu_1395_p3 = ((icmp_ln1035_1_fu_1389_p2[0:0] == 1'b1) ? channeldata_V_1_fu_1379_p4 : ap_sig_allocacmp_oldMax_V_1_load);

assign select_ln167_20_fu_1870_p3 = ((icmp_ln1035_20_fu_1864_p2[0:0] == 1'b1) ? channeldata_V_20_fu_1854_p4 : ap_sig_allocacmp_oldMax_V_20_load);

assign select_ln167_21_fu_1895_p3 = ((icmp_ln1035_21_fu_1889_p2[0:0] == 1'b1) ? channeldata_V_21_fu_1879_p4 : ap_sig_allocacmp_oldMax_V_21_load);

assign select_ln167_22_fu_1920_p3 = ((icmp_ln1035_22_fu_1914_p2[0:0] == 1'b1) ? channeldata_V_22_fu_1904_p4 : ap_sig_allocacmp_oldMax_V_22_load);

assign select_ln167_23_fu_1945_p3 = ((icmp_ln1035_23_fu_1939_p2[0:0] == 1'b1) ? channeldata_V_23_fu_1929_p4 : ap_sig_allocacmp_oldMax_V_23_load);

assign select_ln167_24_fu_1970_p3 = ((icmp_ln1035_24_fu_1964_p2[0:0] == 1'b1) ? channeldata_V_24_fu_1954_p4 : ap_sig_allocacmp_oldMax_V_24_load);

assign select_ln167_25_fu_1995_p3 = ((icmp_ln1035_25_fu_1989_p2[0:0] == 1'b1) ? channeldata_V_25_fu_1979_p4 : ap_sig_allocacmp_oldMax_V_25_load);

assign select_ln167_26_fu_2020_p3 = ((icmp_ln1035_26_fu_2014_p2[0:0] == 1'b1) ? channeldata_V_26_fu_2004_p4 : ap_sig_allocacmp_oldMax_V_26_load);

assign select_ln167_27_fu_2045_p3 = ((icmp_ln1035_27_fu_2039_p2[0:0] == 1'b1) ? channeldata_V_27_fu_2029_p4 : ap_sig_allocacmp_oldMax_V_27_load);

assign select_ln167_28_fu_2070_p3 = ((icmp_ln1035_28_fu_2064_p2[0:0] == 1'b1) ? channeldata_V_28_fu_2054_p4 : ap_sig_allocacmp_oldMax_V_28_load);

assign select_ln167_29_fu_2095_p3 = ((icmp_ln1035_29_fu_2089_p2[0:0] == 1'b1) ? channeldata_V_29_fu_2079_p4 : ap_sig_allocacmp_oldMax_V_29_load);

assign select_ln167_2_fu_1420_p3 = ((icmp_ln1035_2_fu_1414_p2[0:0] == 1'b1) ? channeldata_V_2_fu_1404_p4 : ap_sig_allocacmp_oldMax_V_2_load);

assign select_ln167_30_fu_2120_p3 = ((icmp_ln1035_30_fu_2114_p2[0:0] == 1'b1) ? channeldata_V_30_fu_2104_p4 : ap_sig_allocacmp_oldMax_V_30_load);

assign select_ln167_31_fu_2145_p3 = ((icmp_ln1035_31_fu_2139_p2[0:0] == 1'b1) ? channeldata_V_31_fu_2129_p4 : ap_sig_allocacmp_oldMax_V_31_load);

assign select_ln167_3_fu_1445_p3 = ((icmp_ln1035_3_fu_1439_p2[0:0] == 1'b1) ? channeldata_V_3_fu_1429_p4 : ap_sig_allocacmp_oldMax_V_3_load);

assign select_ln167_4_fu_1470_p3 = ((icmp_ln1035_4_fu_1464_p2[0:0] == 1'b1) ? channeldata_V_4_fu_1454_p4 : ap_sig_allocacmp_oldMax_V_4_load);

assign select_ln167_5_fu_1495_p3 = ((icmp_ln1035_5_fu_1489_p2[0:0] == 1'b1) ? channeldata_V_5_fu_1479_p4 : ap_sig_allocacmp_oldMax_V_5_load);

assign select_ln167_6_fu_1520_p3 = ((icmp_ln1035_6_fu_1514_p2[0:0] == 1'b1) ? channeldata_V_6_fu_1504_p4 : ap_sig_allocacmp_oldMax_V_6_load);

assign select_ln167_7_fu_1545_p3 = ((icmp_ln1035_7_fu_1539_p2[0:0] == 1'b1) ? channeldata_V_7_fu_1529_p4 : ap_sig_allocacmp_oldMax_V_7_load);

assign select_ln167_8_fu_1570_p3 = ((icmp_ln1035_8_fu_1564_p2[0:0] == 1'b1) ? channeldata_V_8_fu_1554_p4 : ap_sig_allocacmp_oldMax_V_8_load);

assign select_ln167_9_fu_1595_p3 = ((icmp_ln1035_9_fu_1589_p2[0:0] == 1'b1) ? channeldata_V_9_fu_1579_p4 : ap_sig_allocacmp_oldMax_V_9_load);

assign select_ln167_fu_1370_p3 = ((icmp_ln1035_fu_1364_p2[0:0] == 1'b1) ? channeldata_V_fu_1360_p1 : ap_sig_allocacmp_oldMax_V_load);

assign zext_ln156_cast_fu_1048_p1 = zext_ln156;

endmodule //StreamingMaxPool_Batch_1_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6
