set SynModuleInfo {
  {SRCNAME StreamingDataWidthConverter_Batch_3 MODELNAME StreamingDataWidthConverter_Batch_3 RTLNAME StreamingDataWidthConverter_Batch_3 IS_TOP 1
    SUBMODULES {
      {MODELNAME StreamingDataWidthConverter_Batch_3_regslice_both RTLNAME StreamingDataWidthConverter_Batch_3_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME StreamingDataWidthConverter_Batch_3_regslice_both_U}
      {MODELNAME StreamingDataWidthConverter_Batch_3_flow_control_loop_pipe_no_ap_cont RTLNAME StreamingDataWidthConverter_Batch_3_flow_control_loop_pipe_no_ap_cont BINDTYPE interface TYPE internal_upc_flow_control INSTNAME StreamingDataWidthConverter_Batch_3_flow_control_loop_pipe_no_ap_cont_U}
    }
  }
}
