-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
-- Version: 2022.2.2
-- Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LabelSelect_Batch_0_LabelSelect_Batch_0_Pipeline_VITIS_LOOP_488_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in0_V_TVALID : IN STD_LOGIC;
    in0_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    in0_V_TREADY : OUT STD_LOGIC;
    conv2_i_i107_i_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv2_i_i107_i_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of LabelSelect_Batch_0_LabelSelect_Batch_0_Pipeline_VITIS_LOOP_488_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln488_fu_87_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in0_V_TDATA_blk_n : STD_LOGIC;
    signal idx_1_fu_44 : STD_LOGIC_VECTOR (3 downto 0);
    signal idx_fu_93_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_block_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_48 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln509_1_fu_123_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_p_load : STD_LOGIC_VECTOR (15 downto 0);
    signal conv2_i_i107_i_fu_52 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln509_fu_115_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_conv2_i_i107_i_load_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmp_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i_i_cast_fu_111_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_117 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component LabelSelect_Batch_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component LabelSelect_Batch_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    conv2_i_i107_i_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_117)) then
                if ((icmp_ln488_fu_87_p2 = ap_const_lv1_0)) then 
                    conv2_i_i107_i_fu_52 <= select_ln509_fu_115_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    conv2_i_i107_i_fu_52 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_117)) then
                if ((icmp_ln488_fu_87_p2 = ap_const_lv1_0)) then 
                    empty_fu_48 <= select_ln509_1_fu_123_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_48 <= ap_const_lv16_8000;
                end if;
            end if; 
        end if;
    end process;

    idx_1_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_117)) then
                if ((icmp_ln488_fu_87_p2 = ap_const_lv1_0)) then 
                    idx_1_fu_44 <= idx_fu_93_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    idx_1_fu_44 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)));
    end process;


    ap_condition_117_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
                ap_condition_117 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln488_fu_87_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_block_1_assign_proc : process(ap_CS_fsm_state1, idx_1_fu_44, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_block_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_block_1 <= idx_1_fu_44;
        end if; 
    end process;


    ap_sig_allocacmp_conv2_i_i107_i_load_1_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, conv2_i_i107_i_fu_52)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_conv2_i_i107_i_load_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_conv2_i_i107_i_load_1 <= conv2_i_i107_i_fu_52;
        end if; 
    end process;


    ap_sig_allocacmp_p_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, empty_fu_48)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_p_load <= ap_const_lv16_8000;
        else 
            ap_sig_allocacmp_p_load <= empty_fu_48;
        end if; 
    end process;

    cmp_fu_105_p2 <= "1" when (signed(in0_V_TDATA) > signed(ap_sig_allocacmp_p_load)) else "0";
    conv2_i_i107_i_out <= conv2_i_i107_i_fu_52;

    conv2_i_i107_i_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln488_fu_87_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            conv2_i_i107_i_out_ap_vld <= ap_const_logic_1;
        else 
            conv2_i_i107_i_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    conv2_i_i_i_cast_fu_111_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_block_1),8));
    icmp_ln488_fu_87_p2 <= "1" when (ap_sig_allocacmp_block_1 = ap_const_lv4_E) else "0";
    idx_fu_93_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_block_1) + unsigned(ap_const_lv4_1));

    in0_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
        if (((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            in0_V_TDATA_blk_n <= in0_V_TVALID;
        else 
            in0_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in0_V_TREADY_assign_proc : process(ap_CS_fsm_state1, in0_V_TVALID, icmp_ln488_fu_87_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (in0_V_TVALID = ap_const_logic_0)))) and (icmp_ln488_fu_87_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in0_V_TREADY <= ap_const_logic_1;
        else 
            in0_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln509_1_fu_123_p3 <= 
        in0_V_TDATA when (cmp_fu_105_p2(0) = '1') else 
        ap_sig_allocacmp_p_load;
    select_ln509_fu_115_p3 <= 
        conv2_i_i_i_cast_fu_111_p1 when (cmp_fu_105_p2(0) = '1') else 
        ap_sig_allocacmp_conv2_i_i107_i_load_1;
end behav;
