// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ConvolutionInputGenerator_1_ConvolutionInputGenerator_1,hls_ip_2022_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.591000,HLS_SYN_LAT=9322,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=840,HLS_SYN_LUT=1364,HLS_VERSION=2022_2_2}" *)

module ConvolutionInputGenerator_1 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [63:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [63:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln191_fu_392_p2;
wire   [0:0] icmp_ln193_fu_418_p2;
wire   [0:0] and_ln239_fu_594_p2;
reg    ap_predicate_op102_read_state1;
reg    ap_predicate_op138_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
reg   [0:0] icmp_ln191_reg_816;
reg   [0:0] icmp_ln191_reg_816_pp0_iter1_reg;
reg   [0:0] icmp_ln193_reg_820;
reg   [0:0] icmp_ln193_reg_820_pp0_iter1_reg;
reg   [0:0] icmp_ln209_reg_824;
reg   [0:0] icmp_ln209_reg_824_pp0_iter1_reg;
reg    ap_predicate_op187_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg   [1:0] ap_CS_iter3_fsm;
reg   [0:0] icmp_ln191_reg_816_pp0_iter2_reg;
reg   [0:0] icmp_ln193_reg_820_pp0_iter2_reg;
reg   [0:0] icmp_ln209_reg_824_pp0_iter2_reg;
reg    ap_predicate_op188_write_state4;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
wire    ap_enable_reg_pp0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
wire   [0:0] icmp_ln209_fu_424_p2;
wire   [5:0] current_line_in_block_fu_450_p2;
reg   [5:0] current_line_in_block_reg_828;
wire   [1:0] add_ln215_fu_462_p2;
reg   [1:0] add_ln215_reg_833;
reg   [1:0] add_ln215_reg_833_pp0_iter1_reg;
wire   [63:0] tmp_fu_717_p6;
wire   [5:0] inputBuf_V_address0;
reg    inputBuf_V_ce0;
wire   [63:0] inputBuf_V_q0;
reg   [5:0] inputBuf_V_address1;
reg    inputBuf_V_ce1;
reg    inputBuf_V_we1;
wire   [5:0] inputBuf_V_1_address0;
reg    inputBuf_V_1_ce0;
wire   [63:0] inputBuf_V_1_q0;
reg   [5:0] inputBuf_V_1_address1;
reg    inputBuf_V_1_ce1;
reg    inputBuf_V_1_we1;
wire   [5:0] inputBuf_V_2_address0;
reg    inputBuf_V_2_ce0;
wire   [63:0] inputBuf_V_2_q0;
reg   [5:0] inputBuf_V_2_address1;
reg    inputBuf_V_2_ce1;
reg    inputBuf_V_2_we1;
wire   [5:0] inputBuf_V_3_address0;
reg    inputBuf_V_3_ce0;
wire   [63:0] inputBuf_V_3_q0;
reg   [5:0] inputBuf_V_3_address1;
reg    inputBuf_V_3_ce1;
reg    inputBuf_V_3_we1;
wire   [63:0] zext_ln242_fu_600_p1;
wire   [63:0] zext_ln196_fu_657_p1;
wire   [63:0] zext_ln215_fu_710_p1;
reg   [13:0] i_fu_82;
wire   [13:0] i_2_fu_398_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_i_1;
reg   [31:0] ofm_y_fu_86;
wire   [31:0] ofm_y_2_fu_546_p3;
reg   [31:0] ap_sig_allocacmp_ofm_y_load;
wire   [0:0] icmp_ln221_fu_474_p2;
wire   [0:0] icmp_ln224_fu_485_p2;
wire   [0:0] icmp_ln227_fu_510_p2;
reg   [31:0] ofm_x_fu_90;
wire   [31:0] ofm_x_1_fu_504_p2;
reg   [31:0] ap_sig_allocacmp_ofm_x_load;
reg   [31:0] ap_sig_allocacmp_ofm_x_load_1;
reg   [31:0] inp_fu_94;
wire   [31:0] inp_3_fu_554_p3;
wire   [31:0] inp_2_fu_669_p2;
reg   [31:0] ap_sig_allocacmp_inp_1;
reg   [31:0] k_y_fu_98;
wire   [31:0] k_y_1_fu_440_p2;
reg   [31:0] ap_sig_allocacmp_k_y_load;
reg   [31:0] current_block_write_fu_102;
wire   [31:0] grp_fu_317_p3;
reg   [31:0] ap_sig_allocacmp_current_block_write_1;
wire   [0:0] grp_fu_295_p2;
reg   [31:0] read_block_fu_106;
wire   [31:0] grp_fu_301_p2;
reg   [31:0] ap_sig_allocacmp_read_block_3;
reg   [31:0] k_x_fu_110;
wire   [31:0] k_x_1_fu_468_p2;
reg   [31:0] ap_sig_allocacmp_k_x_load;
reg   [31:0] ap_sig_allocacmp_k_x_load_1;
reg   [31:0] current_line_fu_114;
wire   [31:0] grp_fu_289_p2;
reg   [31:0] ap_sig_allocacmp_current_line_load_2;
reg   [31:0] ap_sig_allocacmp_current_line_load_3;
reg   [31:0] ap_sig_allocacmp_current_line_load;
reg   [31:0] ap_sig_allocacmp_current_line_load_1;
reg   [31:0] grp_load_fu_283_p1;
reg   [31:0] grp_load_fu_286_p1;
reg   [31:0] counter_internal_block_fu_118;
wire   [31:0] counter_internal_block_3_fu_644_p3;
reg   [31:0] ap_sig_allocacmp_counter_internal_block_1;
wire   [1:0] trunc_ln242_fu_608_p1;
wire   [1:0] trunc_ln196_fu_665_p1;
wire   [31:0] grp_fu_306_p2;
wire   [0:0] grp_fu_311_p2;
wire   [5:0] trunc_ln191_1_fu_414_p1;
wire   [5:0] trunc_ln191_fu_410_p1;
wire   [1:0] trunc_ln210_1_fu_446_p1;
wire   [1:0] add_ln215_1_fu_456_p2;
wire   [1:0] trunc_ln210_fu_436_p1;
wire   [31:0] ofm_y_1_fu_534_p2;
wire   [0:0] icmp_ln230_fu_540_p2;
wire   [0:0] icmp_ln239_fu_582_p2;
wire   [0:0] icmp_ln239_1_fu_588_p2;
wire   [31:0] counter_internal_block_2_fu_632_p2;
wire   [0:0] icmp_ln258_fu_638_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0;
reg    ap_predicate_op110_store_state1;
reg    ap_enable_operation_110;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op146_store_state1;
reg    ap_enable_operation_146;
reg    ap_predicate_op180_load_state2;
reg    ap_enable_operation_180;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op184_load_state3;
reg    ap_enable_operation_184;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op112_store_state1;
reg    ap_enable_operation_112;
reg    ap_predicate_op148_store_state1;
reg    ap_enable_operation_148;
reg    ap_predicate_op179_load_state2;
reg    ap_enable_operation_179;
reg    ap_predicate_op183_load_state3;
reg    ap_enable_operation_183;
reg    ap_predicate_op114_store_state1;
reg    ap_enable_operation_114;
reg    ap_predicate_op150_store_state1;
reg    ap_enable_operation_150;
reg    ap_predicate_op178_load_state2;
reg    ap_enable_operation_178;
reg    ap_predicate_op182_load_state3;
reg    ap_enable_operation_182;
reg    ap_predicate_op116_store_state1;
reg    ap_enable_operation_116;
reg    ap_predicate_op152_store_state1;
reg    ap_enable_operation_152;
reg    ap_predicate_op181_load_state2;
reg    ap_enable_operation_181;
reg    ap_predicate_op185_load_state3;
reg    ap_enable_operation_185;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [63:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
reg    ap_condition_314;
reg    ap_condition_762;
reg    ap_condition_273;
reg    ap_condition_835;
reg    ap_condition_840;
reg    ap_condition_845;
reg    ap_condition_850;
reg    ap_condition_328;
reg    ap_condition_301;
reg    ap_condition_283;
reg    ap_condition_270;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
end

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
inputBuf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_address0),
    .ce0(inputBuf_V_ce0),
    .q0(inputBuf_V_q0),
    .address1(inputBuf_V_address1),
    .ce1(inputBuf_V_ce1),
    .we1(inputBuf_V_we1),
    .d1(in0_V_TDATA_int_regslice)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
inputBuf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_1_address0),
    .ce0(inputBuf_V_1_ce0),
    .q0(inputBuf_V_1_q0),
    .address1(inputBuf_V_1_address1),
    .ce1(inputBuf_V_1_ce1),
    .we1(inputBuf_V_1_we1),
    .d1(in0_V_TDATA_int_regslice)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
inputBuf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_2_address0),
    .ce0(inputBuf_V_2_ce0),
    .q0(inputBuf_V_2_q0),
    .address1(inputBuf_V_2_address1),
    .ce1(inputBuf_V_2_ce1),
    .we1(inputBuf_V_2_we1),
    .d1(in0_V_TDATA_int_regslice)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
inputBuf_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_3_address0),
    .ce0(inputBuf_V_3_ce0),
    .q0(inputBuf_V_3_q0),
    .address1(inputBuf_V_3_address1),
    .ce1(inputBuf_V_3_ce1),
    .we1(inputBuf_V_3_we1),
    .d1(in0_V_TDATA_int_regslice)
);

ConvolutionInputGenerator_1_mux_42_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
mux_42_64_1_1_U1(
    .din0(inputBuf_V_q0),
    .din1(inputBuf_V_1_q0),
    .din2(inputBuf_V_2_q0),
    .din3(inputBuf_V_3_q0),
    .din4(add_ln215_reg_833_pp0_iter1_reg),
    .dout(tmp_fu_717_p6)
);

ConvolutionInputGenerator_1_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

ConvolutionInputGenerator_1_regslice_both #(
    .DataWidth( 64 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

ConvolutionInputGenerator_1_regslice_both #(
    .DataWidth( 64 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_fu_717_p6),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_762)) begin
        if ((1'b1 == ap_condition_314)) begin
            counter_internal_block_fu_118 <= 32'd0;
        end else if (((icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
            counter_internal_block_fu_118 <= counter_internal_block_3_fu_644_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            counter_internal_block_fu_118 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_418_p2 == 1'd1) & (grp_fu_295_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (grp_fu_295_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        current_block_write_fu_102 <= grp_fu_317_p3;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        current_block_write_fu_102 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_418_p2 == 1'd1) & (grp_fu_295_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        current_line_fu_114 <= 32'd0;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (grp_fu_295_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        current_line_fu_114 <= 32'd0;
    end else if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_418_p2 == 1'd1) & (grp_fu_295_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (grp_fu_295_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        current_line_fu_114 <= grp_fu_289_p2;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        current_line_fu_114 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_762)) begin
        if ((icmp_ln191_fu_392_p2 == 1'd0)) begin
            i_fu_82 <= i_2_fu_398_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_762)) begin
        if (((icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
            inp_fu_94 <= inp_2_fu_669_p2;
        end else if ((1'b1 == ap_condition_273)) begin
            inp_fu_94 <= inp_3_fu_554_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            inp_fu_94 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_762)) begin
        if ((1'b1 == ap_condition_273)) begin
            k_x_fu_110 <= 32'd0;
        end else if ((1'b1 == ap_condition_283)) begin
            k_x_fu_110 <= 32'd0;
        end else if ((1'b1 == ap_condition_301)) begin
            k_x_fu_110 <= 32'd0;
        end else if ((1'b1 == ap_condition_328)) begin
            k_x_fu_110 <= k_x_1_fu_468_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_x_fu_110 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_762)) begin
        if ((1'b1 == ap_condition_270)) begin
            k_y_fu_98 <= 32'd0;
        end else if ((1'b1 == ap_condition_301)) begin
            k_y_fu_98 <= k_y_1_fu_440_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_y_fu_98 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_762)) begin
        if ((1'b1 == ap_condition_273)) begin
            ofm_x_fu_90 <= 32'd0;
        end else if ((1'b1 == ap_condition_283)) begin
            ofm_x_fu_90 <= ofm_x_1_fu_504_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ofm_x_fu_90 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_762)) begin
        if ((1'b1 == ap_condition_273)) begin
            ofm_y_fu_86 <= ofm_y_2_fu_546_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ofm_y_fu_86 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_418_p2 == 1'd1) & (grp_fu_295_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (grp_fu_295_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        read_block_fu_106 <= grp_fu_301_p2;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        read_block_fu_106 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0) & (icmp_ln209_fu_424_p2 == 1'd1))) begin
        add_ln215_reg_833 <= add_ln215_fu_462_p2;
        current_line_in_block_reg_828 <= current_line_in_block_fu_450_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        add_ln215_reg_833_pp0_iter1_reg <= add_ln215_reg_833;
        icmp_ln191_reg_816_pp0_iter1_reg <= icmp_ln191_reg_816;
        icmp_ln193_reg_820_pp0_iter1_reg <= icmp_ln193_reg_820;
        icmp_ln209_reg_824_pp0_iter1_reg <= icmp_ln209_reg_824;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln191_reg_816 <= icmp_ln191_fu_392_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln191_reg_816_pp0_iter2_reg <= icmp_ln191_reg_816_pp0_iter1_reg;
        icmp_ln193_reg_820_pp0_iter2_reg <= icmp_ln193_reg_820_pp0_iter1_reg;
        icmp_ln209_reg_824_pp0_iter2_reg <= icmp_ln209_reg_824_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        icmp_ln193_reg_820 <= icmp_ln193_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        icmp_ln209_reg_824 <= icmp_ln209_fu_424_p2;
    end
end

always @ (*) begin
    if ((((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_counter_internal_block_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_counter_internal_block_1 = counter_internal_block_fu_118;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_block_write_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_block_write_1 = current_block_write_fu_102;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load = current_line_fu_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_1 = current_line_fu_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_2 = current_line_fu_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_3 = current_line_fu_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 14'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_82;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_inp_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_inp_1 = inp_fu_94;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_x_load = 32'd0;
    end else begin
        ap_sig_allocacmp_k_x_load = k_x_fu_110;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_x_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_k_x_load_1 = k_x_fu_110;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_y_load = 32'd0;
    end else begin
        ap_sig_allocacmp_k_y_load = k_y_fu_98;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_x_load = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_x_load = ofm_x_fu_90;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_x_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_x_load_1 = ofm_x_fu_90;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_y_load = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_y_load = ofm_y_fu_86;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_read_block_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_read_block_3 = read_block_fu_106;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        if ((icmp_ln193_fu_418_p2 == 1'd1)) begin
            grp_load_fu_283_p1 = ap_sig_allocacmp_current_line_load;
        end else if (((1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0))) begin
            grp_load_fu_283_p1 = ap_sig_allocacmp_current_line_load_2;
        end else begin
            grp_load_fu_283_p1 = 'bx;
        end
    end else begin
        grp_load_fu_283_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        if ((icmp_ln193_fu_418_p2 == 1'd1)) begin
            grp_load_fu_286_p1 = ap_sig_allocacmp_current_line_load_1;
        end else if (((1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0))) begin
            grp_load_fu_286_p1 = ap_sig_allocacmp_current_line_load_3;
        end else begin
            grp_load_fu_286_p1 = 'bx;
        end
    end else begin
        grp_load_fu_286_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op138_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op102_read_state1 == 1'b1)))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op138_read_state1 == 1'b1)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op102_read_state1 == 1'b1)))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_665_p1 == 2'd1) & (icmp_ln193_fu_418_p2 == 1'd1))) begin
            inputBuf_V_1_address1 = zext_ln196_fu_657_p1;
        end else if ((1'b1 == ap_condition_835)) begin
            inputBuf_V_1_address1 = zext_ln242_fu_600_p1;
        end else begin
            inputBuf_V_1_address1 = 'bx;
        end
    end else begin
        inputBuf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_1_ce0 = 1'b1;
    end else begin
        inputBuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd1) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_1_ce1 = 1'b1;
    end else begin
        inputBuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd1) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_1_we1 = 1'b1;
    end else begin
        inputBuf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_665_p1 == 2'd2) & (icmp_ln193_fu_418_p2 == 1'd1))) begin
            inputBuf_V_2_address1 = zext_ln196_fu_657_p1;
        end else if ((1'b1 == ap_condition_840)) begin
            inputBuf_V_2_address1 = zext_ln242_fu_600_p1;
        end else begin
            inputBuf_V_2_address1 = 'bx;
        end
    end else begin
        inputBuf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_2_ce0 = 1'b1;
    end else begin
        inputBuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd2) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd2) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_2_ce1 = 1'b1;
    end else begin
        inputBuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd2) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd2) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_2_we1 = 1'b1;
    end else begin
        inputBuf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_665_p1 == 2'd3) & (icmp_ln193_fu_418_p2 == 1'd1))) begin
            inputBuf_V_3_address1 = zext_ln196_fu_657_p1;
        end else if ((1'b1 == ap_condition_845)) begin
            inputBuf_V_3_address1 = zext_ln242_fu_600_p1;
        end else begin
            inputBuf_V_3_address1 = 'bx;
        end
    end else begin
        inputBuf_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_3_ce0 = 1'b1;
    end else begin
        inputBuf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd3) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd3) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_3_ce1 = 1'b1;
    end else begin
        inputBuf_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd3) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd3) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_3_we1 = 1'b1;
    end else begin
        inputBuf_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_392_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_665_p1 == 2'd0) & (icmp_ln193_fu_418_p2 == 1'd1))) begin
            inputBuf_V_address1 = zext_ln196_fu_657_p1;
        end else if ((1'b1 == ap_condition_850)) begin
            inputBuf_V_address1 = zext_ln242_fu_600_p1;
        end else begin
            inputBuf_V_address1 = 'bx;
        end
    end else begin
        inputBuf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_ce0 = 1'b1;
    end else begin
        inputBuf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd0) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd0) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_ce1 = 1'b1;
    end else begin
        inputBuf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_665_p1 == 2'd0) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_608_p1 == 2'd0) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0)))) begin
        inputBuf_V_we1 = 1'b1;
    end else begin
        inputBuf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op187_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_predicate_op188_write_state4 == 1'b1)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (ap_predicate_op187_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & ~(((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))) & ~((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else if ((~((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))) & (icmp_ln191_reg_816_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter3_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign add_ln215_1_fu_456_p2 = (trunc_ln210_1_fu_446_p1 + 2'd1);

assign add_ln215_fu_462_p2 = (add_ln215_1_fu_456_p2 + trunc_ln210_fu_436_p1);

assign and_ln239_fu_594_p2 = (icmp_ln239_fu_582_p2 & icmp_ln239_1_fu_588_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_iter0_fsm_state1 == ap_CS_iter0_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (regslice_both_out_V_U_apdone_blk == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_condition_270 = ((icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0) & (icmp_ln224_fu_485_p2 == 1'd1) & (icmp_ln221_fu_474_p2 == 1'd1) & (icmp_ln209_fu_424_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_273 = ((icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0) & (icmp_ln227_fu_510_p2 == 1'd1) & (icmp_ln224_fu_485_p2 == 1'd1) & (icmp_ln221_fu_474_p2 == 1'd1) & (icmp_ln209_fu_424_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_283 = ((icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0) & (icmp_ln227_fu_510_p2 == 1'd0) & (icmp_ln224_fu_485_p2 == 1'd1) & (icmp_ln221_fu_474_p2 == 1'd1) & (icmp_ln209_fu_424_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_301 = ((icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0) & (icmp_ln224_fu_485_p2 == 1'd0) & (icmp_ln221_fu_474_p2 == 1'd1) & (icmp_ln209_fu_424_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_314 = ((icmp_ln193_fu_418_p2 == 1'd1) & (grp_fu_295_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_328 = ((icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0) & (icmp_ln221_fu_474_p2 == 1'd0) & (icmp_ln209_fu_424_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_762 = (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op187_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op138_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op102_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op188_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_835 = ((trunc_ln242_fu_608_p1 == 2'd1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_840 = ((trunc_ln242_fu_608_p1 == 2'd2) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_845 = ((trunc_ln242_fu_608_p1 == 2'd3) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_850 = ((trunc_ln242_fu_608_p1 == 2'd0) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0));
end

always @ (*) begin
    ap_enable_operation_110 = (ap_predicate_op110_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_112 = (ap_predicate_op112_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_114 = (ap_predicate_op114_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_116 = (ap_predicate_op116_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_146 = (ap_predicate_op146_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_148 = (ap_predicate_op148_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_150 = (ap_predicate_op150_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_152 = (ap_predicate_op152_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_178 = (ap_predicate_op178_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_179 = (ap_predicate_op179_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_180 = (ap_predicate_op180_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_181 = (ap_predicate_op181_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_182 = (ap_predicate_op182_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_183 = (ap_predicate_op183_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_184 = (ap_predicate_op184_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_185 = (ap_predicate_op185_load_state3 == 1'b1);
end

assign ap_enable_reg_pp0_iter0 = 1'b0;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((1'b1 == ap_CS_iter0_fsm_state1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3));
end

assign ap_loop_exit_ready_pp0_iter3_reg = 1'b0;

always @ (*) begin
    ap_predicate_op102_read_state1 = ((1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op110_store_state1 = ((trunc_ln242_fu_608_p1 == 2'd2) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op112_store_state1 = ((trunc_ln242_fu_608_p1 == 2'd1) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op114_store_state1 = ((trunc_ln242_fu_608_p1 == 2'd0) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op116_store_state1 = ((trunc_ln242_fu_608_p1 == 2'd3) & (1'd1 == and_ln239_fu_594_p2) & (icmp_ln193_fu_418_p2 == 1'd0) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op138_read_state1 = ((icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op146_store_state1 = ((trunc_ln196_fu_665_p1 == 2'd2) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op148_store_state1 = ((trunc_ln196_fu_665_p1 == 2'd1) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op150_store_state1 = ((trunc_ln196_fu_665_p1 == 2'd0) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op152_store_state1 = ((trunc_ln196_fu_665_p1 == 2'd3) & (icmp_ln193_fu_418_p2 == 1'd1) & (icmp_ln191_fu_392_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op178_load_state2 = ((icmp_ln209_reg_824 == 1'd1) & (icmp_ln193_reg_820 == 1'd0) & (icmp_ln191_reg_816 == 1'd0));
end

always @ (*) begin
    ap_predicate_op179_load_state2 = ((icmp_ln209_reg_824 == 1'd1) & (icmp_ln193_reg_820 == 1'd0) & (icmp_ln191_reg_816 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_load_state2 = ((icmp_ln209_reg_824 == 1'd1) & (icmp_ln193_reg_820 == 1'd0) & (icmp_ln191_reg_816 == 1'd0));
end

always @ (*) begin
    ap_predicate_op181_load_state2 = ((icmp_ln209_reg_824 == 1'd1) & (icmp_ln193_reg_820 == 1'd0) & (icmp_ln191_reg_816 == 1'd0));
end

always @ (*) begin
    ap_predicate_op182_load_state3 = ((icmp_ln209_reg_824_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_820_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_816_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op183_load_state3 = ((icmp_ln209_reg_824_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_820_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_816_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op184_load_state3 = ((icmp_ln209_reg_824_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_820_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_816_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op185_load_state3 = ((icmp_ln209_reg_824_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_820_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_816_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op187_write_state3 = ((icmp_ln209_reg_824_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_820_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_816_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op188_write_state4 = ((icmp_ln193_reg_820_pp0_iter2_reg == 1'd0) & (icmp_ln191_reg_816_pp0_iter2_reg == 1'd0) & (icmp_ln209_reg_824_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign counter_internal_block_2_fu_632_p2 = (ap_sig_allocacmp_counter_internal_block_1 + 32'd1);

assign counter_internal_block_3_fu_644_p3 = ((icmp_ln258_fu_638_p2[0:0] == 1'b1) ? 32'd0 : counter_internal_block_2_fu_632_p2);

assign current_line_in_block_fu_450_p2 = (trunc_ln191_1_fu_414_p1 + trunc_ln191_fu_410_p1);

assign grp_fu_289_p2 = (grp_load_fu_286_p1 + 32'd1);

assign grp_fu_295_p2 = ((grp_fu_289_p2 == 32'd34) ? 1'b1 : 1'b0);

assign grp_fu_301_p2 = (ap_sig_allocacmp_read_block_3 + 32'd1);

assign grp_fu_306_p2 = (ap_sig_allocacmp_current_block_write_1 + 32'd1);

assign grp_fu_311_p2 = ((grp_fu_306_p2 == 32'd4) ? 1'b1 : 1'b0);

assign grp_fu_317_p3 = ((grp_fu_311_p2[0:0] == 1'b1) ? 32'd0 : grp_fu_306_p2);

assign i_2_fu_398_p2 = (ap_sig_allocacmp_i_1 + 14'd1);

assign icmp_ln191_fu_392_p2 = ((ap_sig_allocacmp_i_1 == 14'd9318) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_418_p2 = ((ap_sig_allocacmp_inp_1 < 32'd102) ? 1'b1 : 1'b0);

assign icmp_ln209_fu_424_p2 = ((ap_sig_allocacmp_counter_internal_block_1 < 32'd287) ? 1'b1 : 1'b0);

assign icmp_ln221_fu_474_p2 = ((k_x_1_fu_468_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_485_p2 = ((k_y_1_fu_440_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_510_p2 = ((ofm_x_1_fu_504_p2 == 32'd32) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_540_p2 = ((ofm_y_1_fu_534_p2 == 32'd32) ? 1'b1 : 1'b0);

assign icmp_ln239_1_fu_588_p2 = ((ap_sig_allocacmp_read_block_3 < 32'd34) ? 1'b1 : 1'b0);

assign icmp_ln239_fu_582_p2 = ((ap_sig_allocacmp_counter_internal_block_1 < 32'd33) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_638_p2 = ((counter_internal_block_2_fu_632_p2 == 32'd287) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign inp_2_fu_669_p2 = (ap_sig_allocacmp_inp_1 + 32'd1);

assign inp_3_fu_554_p3 = ((icmp_ln230_fu_540_p2[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_inp_1);

assign inputBuf_V_1_address0 = zext_ln215_fu_710_p1;

assign inputBuf_V_2_address0 = zext_ln215_fu_710_p1;

assign inputBuf_V_3_address0 = zext_ln215_fu_710_p1;

assign inputBuf_V_address0 = zext_ln215_fu_710_p1;

assign k_x_1_fu_468_p2 = (ap_sig_allocacmp_k_x_load_1 + 32'd1);

assign k_y_1_fu_440_p2 = (ap_sig_allocacmp_k_y_load + 32'd1);

assign ofm_x_1_fu_504_p2 = (ap_sig_allocacmp_ofm_x_load_1 + 32'd1);

assign ofm_y_1_fu_534_p2 = (ap_sig_allocacmp_ofm_y_load + 32'd1);

assign ofm_y_2_fu_546_p3 = ((icmp_ln230_fu_540_p2[0:0] == 1'b1) ? 32'd0 : ofm_y_1_fu_534_p2);

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign trunc_ln191_1_fu_414_p1 = ap_sig_allocacmp_ofm_x_load[5:0];

assign trunc_ln191_fu_410_p1 = ap_sig_allocacmp_k_x_load[5:0];

assign trunc_ln196_fu_665_p1 = ap_sig_allocacmp_current_block_write_1[1:0];

assign trunc_ln210_1_fu_446_p1 = ap_sig_allocacmp_current_block_write_1[1:0];

assign trunc_ln210_fu_436_p1 = ap_sig_allocacmp_k_y_load[1:0];

assign trunc_ln242_fu_608_p1 = ap_sig_allocacmp_current_block_write_1[1:0];

assign zext_ln196_fu_657_p1 = grp_load_fu_283_p1;

assign zext_ln215_fu_710_p1 = current_line_in_block_reg_828;

assign zext_ln242_fu_600_p1 = grp_load_fu_283_p1;

always @ (posedge ap_clk) begin
    ap_enable_reg_pp0_iter1 <= 1'b0;
    ap_enable_reg_pp0_iter2 <= 1'b0;
end

endmodule //ConvolutionInputGenerator_1
