# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/finn_design/finn_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design || ORIG_REF_NAME==finn_design} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_0/finn_design_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_0 || ORIG_REF_NAME==finn_design_fifo_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_0_1_0/finn_design_StreamingFIFO_0_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_0_1_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_0_1_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_Thresholding_Batch_0_0/finn_design_Thresholding_Batch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_Thresholding_Batch_0_0 || ORIG_REF_NAME==finn_design_Thresholding_Batch_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_1/finn_design_fifo_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_1 || ORIG_REF_NAME==finn_design_fifo_1} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_1_1_0/finn_design_StreamingFIFO_1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_1_1_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_1_1_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MatrixVectorActivation_0_0/finn_design_MatrixVectorActivation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MatrixVectorActivation_0_0 || ORIG_REF_NAME==finn_design_MatrixVectorActivation_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_2_0/finn_design_StreamingFIFO_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_2_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_2_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MatrixVectorActivation_1_0/finn_design_MatrixVectorActivation_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MatrixVectorActivation_1_0 || ORIG_REF_NAME==finn_design_MatrixVectorActivation_1_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MatrixVectorActivation_2_0/finn_design_MatrixVectorActivation_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MatrixVectorActivation_2_0 || ORIG_REF_NAME==finn_design_MatrixVectorActivation_2_0} -quiet] -quiet

# XDC: /tmp/FINN_build_mlp27k_w4a8_ft_clean/vivado_stitch_proj_8ba8a6h2/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/finn_design_ooc.xdc
