
####################################################################################
# Generated by Vivado 2022.2.2 built on 'Tue Feb 21 19:59:23 MST 2023' by 'xbuild'
# Command Used: write_xdc finn_design.xdc
####################################################################################


####################################################################################
# Constraints from file : 'xpm_cdc_sync_rst.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_srst
current_instance finn_design_i/StreamingFIFO_0_0/fifo/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_srst
current_instance -quiet
current_instance finn_design_i/StreamingFIFO_1_0/fifo/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]



####################################################################################
# Constraints from file : 'xpm_fifo_rst_axis.tcl'
####################################################################################








# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
