// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Thresholding_Batch_0_Thresholding_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
wire   [0:0] icmp_ln295_fu_329_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] icmp_ln295_reg_2747;
reg   [0:0] icmp_ln295_reg_2747_pp0_iter2_reg;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
wire   [0:0] icmp_ln295_reg_2747_pp0_iter0_reg;
reg   [0:0] icmp_ln295_reg_2747_pp0_iter1_reg;
reg   [7:0] inElem_reg_2751;
reg   [7:0] inElem_reg_2751_pp0_iter1_reg;
wire   [0:0] icmp_ln1039_32_fu_501_p2;
reg   [0:0] icmp_ln1039_32_reg_2865;
wire   [0:0] icmp_ln1039_126_fu_517_p2;
reg   [0:0] icmp_ln1039_126_reg_2870;
wire   [1:0] add_ln840_1_fu_529_p2;
reg   [1:0] add_ln840_1_reg_2875;
wire   [1:0] add_ln840_2_fu_535_p2;
reg   [1:0] add_ln840_2_reg_2880;
wire   [1:0] add_ln840_3_fu_541_p2;
reg   [1:0] add_ln840_3_reg_2885;
wire   [2:0] add_ln840_8_fu_567_p2;
reg   [2:0] add_ln840_8_reg_2890;
wire   [2:0] add_ln840_11_fu_593_p2;
reg   [2:0] add_ln840_11_reg_2895;
wire   [3:0] add_ln840_13_fu_1061_p2;
reg   [3:0] add_ln840_13_reg_2900;
wire   [3:0] add_ln840_20_fu_1127_p2;
reg   [3:0] add_ln840_20_reg_2905;
wire   [3:0] add_ln840_27_fu_1193_p2;
reg   [3:0] add_ln840_27_reg_2910;
wire   [3:0] add_ln840_36_fu_1259_p2;
reg   [3:0] add_ln840_36_reg_2915;
wire   [3:0] add_ln840_43_fu_1325_p2;
reg   [3:0] add_ln840_43_reg_2920;
wire   [3:0] add_ln840_51_fu_1391_p2;
reg   [3:0] add_ln840_51_reg_2925;
wire   [3:0] add_ln840_58_fu_1457_p2;
reg   [3:0] add_ln840_58_reg_2930;
wire   [5:0] add_ln840_61_fu_2102_p2;
reg   [5:0] add_ln840_61_reg_2935;
wire   [3:0] add_ln840_68_fu_2168_p2;
reg   [3:0] add_ln840_68_reg_2940;
wire   [3:0] add_ln840_75_fu_2234_p2;
reg   [3:0] add_ln840_75_reg_2945;
wire   [3:0] add_ln840_83_fu_2300_p2;
reg   [3:0] add_ln840_83_reg_2950;
wire   [3:0] add_ln840_90_fu_2366_p2;
reg   [3:0] add_ln840_90_reg_2955;
wire   [3:0] add_ln840_99_fu_2432_p2;
reg   [3:0] add_ln840_99_reg_2960;
wire   [3:0] add_ln840_106_fu_2498_p2;
reg   [3:0] add_ln840_106_reg_2965;
wire   [3:0] add_ln840_114_fu_2564_p2;
reg   [3:0] add_ln840_114_reg_2970;
wire   [3:0] add_ln840_121_fu_2630_p2;
reg   [3:0] add_ln840_121_reg_2975;
reg   [12:0] i_fu_304;
wire   [12:0] i_2_fu_335_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_i_1;
wire   [0:0] result_V_fu_341_p2;
wire   [0:0] icmp_ln1039_fu_351_p2;
wire   [0:0] icmp_ln1039_1_fu_361_p2;
wire   [0:0] icmp_ln1039_2_fu_371_p2;
wire   [0:0] icmp_ln1039_3_fu_381_p2;
wire   [0:0] icmp_ln1039_4_fu_391_p2;
wire   [0:0] icmp_ln1039_5_fu_401_p2;
wire   [0:0] icmp_ln1039_6_fu_411_p2;
wire   [0:0] icmp_ln1039_7_fu_421_p2;
wire   [0:0] icmp_ln1039_8_fu_431_p2;
wire   [0:0] icmp_ln1039_9_fu_441_p2;
wire   [0:0] icmp_ln1039_10_fu_451_p2;
wire   [0:0] icmp_ln1039_11_fu_461_p2;
wire   [0:0] icmp_ln1039_12_fu_471_p2;
wire   [0:0] icmp_ln1039_13_fu_481_p2;
wire   [2:0] tmp_fu_491_p4;
wire   [1:0] tmp_1_fu_507_p4;
wire   [1:0] zext_ln215_fu_347_p1;
wire   [1:0] zext_ln1039_1_fu_367_p1;
wire   [1:0] add_ln840_fu_523_p2;
wire   [1:0] zext_ln1039_fu_357_p1;
wire   [1:0] zext_ln1039_2_fu_377_p1;
wire   [1:0] zext_ln1039_3_fu_387_p1;
wire   [1:0] zext_ln1039_4_fu_397_p1;
wire   [1:0] zext_ln1039_5_fu_407_p1;
wire   [1:0] zext_ln1039_6_fu_417_p1;
wire   [1:0] zext_ln1039_7_fu_427_p1;
wire   [1:0] add_ln840_6_fu_547_p2;
wire   [1:0] zext_ln1039_8_fu_437_p1;
wire   [1:0] zext_ln1039_9_fu_447_p1;
wire   [1:0] add_ln840_7_fu_557_p2;
wire   [2:0] zext_ln840_6_fu_563_p1;
wire   [2:0] zext_ln840_5_fu_553_p1;
wire   [1:0] zext_ln1039_10_fu_457_p1;
wire   [1:0] zext_ln1039_11_fu_467_p1;
wire   [1:0] add_ln840_9_fu_573_p2;
wire   [1:0] zext_ln1039_12_fu_477_p1;
wire   [1:0] zext_ln1039_13_fu_487_p1;
wire   [1:0] add_ln840_10_fu_583_p2;
wire   [2:0] zext_ln840_9_fu_589_p1;
wire   [2:0] zext_ln840_8_fu_579_p1;
wire   [0:0] icmp_ln1039_14_fu_604_p2;
wire   [0:0] icmp_ln1039_16_fu_616_p2;
wire   [0:0] icmp_ln1039_17_fu_625_p2;
wire   [0:0] icmp_ln1039_18_fu_634_p2;
wire   [0:0] icmp_ln1039_19_fu_643_p2;
wire   [0:0] icmp_ln1039_20_fu_652_p2;
wire   [0:0] icmp_ln1039_21_fu_661_p2;
wire   [0:0] icmp_ln1039_22_fu_670_p2;
wire   [0:0] icmp_ln1039_23_fu_679_p2;
wire   [0:0] icmp_ln1039_24_fu_688_p2;
wire   [0:0] icmp_ln1039_25_fu_697_p2;
wire   [0:0] icmp_ln1039_26_fu_706_p2;
wire   [0:0] icmp_ln1039_27_fu_715_p2;
wire   [0:0] icmp_ln1039_28_fu_724_p2;
wire   [0:0] icmp_ln1039_29_fu_733_p2;
wire   [0:0] icmp_ln1039_30_fu_742_p2;
wire   [0:0] icmp_ln1039_31_fu_751_p2;
wire   [0:0] icmp_ln1039_33_fu_763_p2;
wire   [0:0] icmp_ln1039_34_fu_772_p2;
wire   [0:0] icmp_ln1039_35_fu_781_p2;
wire   [0:0] icmp_ln1039_36_fu_790_p2;
wire   [0:0] icmp_ln1039_37_fu_799_p2;
wire   [0:0] icmp_ln1039_38_fu_808_p2;
wire   [0:0] icmp_ln1039_39_fu_817_p2;
wire   [0:0] icmp_ln1039_40_fu_826_p2;
wire   [0:0] icmp_ln1039_41_fu_835_p2;
wire   [0:0] icmp_ln1039_42_fu_844_p2;
wire   [0:0] icmp_ln1039_43_fu_853_p2;
wire   [0:0] icmp_ln1039_44_fu_862_p2;
wire   [0:0] icmp_ln1039_45_fu_871_p2;
wire   [0:0] icmp_ln1039_46_fu_880_p2;
wire   [0:0] icmp_ln1039_47_fu_889_p2;
wire   [0:0] icmp_ln1039_48_fu_898_p2;
wire   [0:0] icmp_ln1039_49_fu_907_p2;
wire   [0:0] icmp_ln1039_50_fu_916_p2;
wire   [0:0] icmp_ln1039_51_fu_925_p2;
wire   [0:0] icmp_ln1039_52_fu_934_p2;
wire   [0:0] icmp_ln1039_53_fu_943_p2;
wire   [0:0] icmp_ln1039_54_fu_952_p2;
wire   [0:0] icmp_ln1039_55_fu_961_p2;
wire   [0:0] icmp_ln1039_56_fu_970_p2;
wire   [0:0] icmp_ln1039_57_fu_979_p2;
wire   [0:0] icmp_ln1039_58_fu_988_p2;
wire   [0:0] icmp_ln1039_59_fu_997_p2;
wire   [0:0] icmp_ln1039_60_fu_1006_p2;
wire   [0:0] icmp_ln1039_61_fu_1015_p2;
wire   [2:0] zext_ln840_3_fu_1030_p1;
wire   [2:0] zext_ln840_2_fu_1027_p1;
wire   [2:0] add_ln840_4_fu_1033_p2;
wire   [2:0] zext_ln840_1_fu_1024_p1;
wire   [2:0] add_ln840_5_fu_1039_p2;
wire   [3:0] zext_ln840_10_fu_1052_p1;
wire   [3:0] zext_ln840_7_fu_1049_p1;
wire   [3:0] add_ln840_12_fu_1055_p2;
wire   [3:0] zext_ln840_4_fu_1045_p1;
wire   [1:0] zext_ln1039_14_fu_609_p1;
wire   [1:0] zext_ln1039_15_fu_613_p1;
wire   [1:0] add_ln840_14_fu_1067_p2;
wire   [1:0] zext_ln1039_16_fu_621_p1;
wire   [1:0] zext_ln1039_17_fu_630_p1;
wire   [1:0] add_ln840_15_fu_1077_p2;
wire   [2:0] zext_ln840_13_fu_1083_p1;
wire   [2:0] zext_ln840_12_fu_1073_p1;
wire   [2:0] add_ln840_16_fu_1087_p2;
wire   [1:0] zext_ln1039_18_fu_639_p1;
wire   [1:0] zext_ln1039_19_fu_648_p1;
wire   [1:0] add_ln840_17_fu_1097_p2;
wire   [1:0] zext_ln1039_20_fu_657_p1;
wire   [1:0] zext_ln1039_21_fu_666_p1;
wire   [1:0] add_ln840_18_fu_1107_p2;
wire   [2:0] zext_ln840_16_fu_1113_p1;
wire   [2:0] zext_ln840_15_fu_1103_p1;
wire   [2:0] add_ln840_19_fu_1117_p2;
wire   [3:0] zext_ln840_17_fu_1123_p1;
wire   [3:0] zext_ln840_14_fu_1093_p1;
wire   [1:0] zext_ln1039_22_fu_675_p1;
wire   [1:0] zext_ln1039_23_fu_684_p1;
wire   [1:0] add_ln840_21_fu_1133_p2;
wire   [1:0] zext_ln1039_24_fu_693_p1;
wire   [1:0] zext_ln1039_25_fu_702_p1;
wire   [1:0] add_ln840_22_fu_1143_p2;
wire   [2:0] zext_ln840_20_fu_1149_p1;
wire   [2:0] zext_ln840_19_fu_1139_p1;
wire   [2:0] add_ln840_23_fu_1153_p2;
wire   [1:0] zext_ln1039_26_fu_711_p1;
wire   [1:0] zext_ln1039_27_fu_720_p1;
wire   [1:0] add_ln840_24_fu_1163_p2;
wire   [1:0] zext_ln1039_28_fu_729_p1;
wire   [1:0] zext_ln1039_29_fu_738_p1;
wire   [1:0] add_ln840_25_fu_1173_p2;
wire   [2:0] zext_ln840_23_fu_1179_p1;
wire   [2:0] zext_ln840_22_fu_1169_p1;
wire   [2:0] add_ln840_26_fu_1183_p2;
wire   [3:0] zext_ln840_24_fu_1189_p1;
wire   [3:0] zext_ln840_21_fu_1159_p1;
wire   [1:0] zext_ln1039_30_fu_747_p1;
wire   [1:0] zext_ln1039_31_fu_756_p1;
wire   [1:0] add_ln840_30_fu_1199_p2;
wire   [1:0] zext_ln1039_32_fu_760_p1;
wire   [1:0] zext_ln1039_33_fu_768_p1;
wire   [1:0] add_ln840_31_fu_1209_p2;
wire   [2:0] zext_ln840_28_fu_1215_p1;
wire   [2:0] zext_ln840_27_fu_1205_p1;
wire   [2:0] add_ln840_32_fu_1219_p2;
wire   [1:0] zext_ln1039_34_fu_777_p1;
wire   [1:0] zext_ln1039_35_fu_786_p1;
wire   [1:0] add_ln840_33_fu_1229_p2;
wire   [1:0] zext_ln1039_36_fu_795_p1;
wire   [1:0] zext_ln1039_37_fu_804_p1;
wire   [1:0] add_ln840_34_fu_1239_p2;
wire   [2:0] zext_ln840_31_fu_1245_p1;
wire   [2:0] zext_ln840_30_fu_1235_p1;
wire   [2:0] add_ln840_35_fu_1249_p2;
wire   [3:0] zext_ln840_32_fu_1255_p1;
wire   [3:0] zext_ln840_29_fu_1225_p1;
wire   [1:0] zext_ln1039_38_fu_813_p1;
wire   [1:0] zext_ln1039_39_fu_822_p1;
wire   [1:0] add_ln840_37_fu_1265_p2;
wire   [1:0] zext_ln1039_40_fu_831_p1;
wire   [1:0] zext_ln1039_41_fu_840_p1;
wire   [1:0] add_ln840_38_fu_1275_p2;
wire   [2:0] zext_ln840_35_fu_1281_p1;
wire   [2:0] zext_ln840_34_fu_1271_p1;
wire   [2:0] add_ln840_39_fu_1285_p2;
wire   [1:0] zext_ln1039_42_fu_849_p1;
wire   [1:0] zext_ln1039_43_fu_858_p1;
wire   [1:0] add_ln840_40_fu_1295_p2;
wire   [1:0] zext_ln1039_44_fu_867_p1;
wire   [1:0] zext_ln1039_45_fu_876_p1;
wire   [1:0] add_ln840_41_fu_1305_p2;
wire   [2:0] zext_ln840_38_fu_1311_p1;
wire   [2:0] zext_ln840_37_fu_1301_p1;
wire   [2:0] add_ln840_42_fu_1315_p2;
wire   [3:0] zext_ln840_39_fu_1321_p1;
wire   [3:0] zext_ln840_36_fu_1291_p1;
wire   [1:0] zext_ln1039_46_fu_885_p1;
wire   [1:0] zext_ln1039_47_fu_894_p1;
wire   [1:0] add_ln840_45_fu_1331_p2;
wire   [1:0] zext_ln1039_48_fu_903_p1;
wire   [1:0] zext_ln1039_49_fu_912_p1;
wire   [1:0] add_ln840_46_fu_1341_p2;
wire   [2:0] zext_ln840_43_fu_1347_p1;
wire   [2:0] zext_ln840_42_fu_1337_p1;
wire   [2:0] add_ln840_47_fu_1351_p2;
wire   [1:0] zext_ln1039_50_fu_921_p1;
wire   [1:0] zext_ln1039_51_fu_930_p1;
wire   [1:0] add_ln840_48_fu_1361_p2;
wire   [1:0] zext_ln1039_52_fu_939_p1;
wire   [1:0] zext_ln1039_53_fu_948_p1;
wire   [1:0] add_ln840_49_fu_1371_p2;
wire   [2:0] zext_ln840_46_fu_1377_p1;
wire   [2:0] zext_ln840_45_fu_1367_p1;
wire   [2:0] add_ln840_50_fu_1381_p2;
wire   [3:0] zext_ln840_47_fu_1387_p1;
wire   [3:0] zext_ln840_44_fu_1357_p1;
wire   [1:0] zext_ln1039_54_fu_957_p1;
wire   [1:0] zext_ln1039_55_fu_966_p1;
wire   [1:0] add_ln840_52_fu_1397_p2;
wire   [1:0] zext_ln1039_56_fu_975_p1;
wire   [1:0] zext_ln1039_57_fu_984_p1;
wire   [1:0] add_ln840_53_fu_1407_p2;
wire   [2:0] zext_ln840_50_fu_1413_p1;
wire   [2:0] zext_ln840_49_fu_1403_p1;
wire   [2:0] add_ln840_54_fu_1417_p2;
wire   [1:0] zext_ln1039_58_fu_993_p1;
wire   [1:0] zext_ln1039_59_fu_1002_p1;
wire   [1:0] add_ln840_55_fu_1427_p2;
wire   [1:0] zext_ln1039_60_fu_1011_p1;
wire   [1:0] zext_ln1039_61_fu_1020_p1;
wire   [1:0] add_ln840_56_fu_1437_p2;
wire   [2:0] zext_ln840_53_fu_1443_p1;
wire   [2:0] zext_ln840_52_fu_1433_p1;
wire   [2:0] add_ln840_57_fu_1447_p2;
wire   [3:0] zext_ln840_54_fu_1453_p1;
wire   [3:0] zext_ln840_51_fu_1423_p1;
wire   [0:0] icmp_ln1039_62_fu_1463_p2;
wire   [0:0] icmp_ln1039_63_fu_1472_p2;
wire   [0:0] icmp_ln1039_64_fu_1481_p2;
wire   [0:0] icmp_ln1039_65_fu_1490_p2;
wire   [0:0] icmp_ln1039_66_fu_1499_p2;
wire   [0:0] icmp_ln1039_67_fu_1508_p2;
wire   [0:0] icmp_ln1039_68_fu_1517_p2;
wire   [0:0] icmp_ln1039_69_fu_1526_p2;
wire   [0:0] icmp_ln1039_70_fu_1535_p2;
wire   [0:0] icmp_ln1039_71_fu_1544_p2;
wire   [0:0] icmp_ln1039_72_fu_1553_p2;
wire   [0:0] icmp_ln1039_73_fu_1562_p2;
wire   [0:0] icmp_ln1039_74_fu_1571_p2;
wire   [0:0] icmp_ln1039_75_fu_1580_p2;
wire   [0:0] icmp_ln1039_76_fu_1589_p2;
wire   [0:0] icmp_ln1039_77_fu_1598_p2;
wire   [0:0] icmp_ln1039_78_fu_1607_p2;
wire   [0:0] icmp_ln1039_79_fu_1616_p2;
wire   [0:0] icmp_ln1039_80_fu_1625_p2;
wire   [0:0] icmp_ln1039_81_fu_1634_p2;
wire   [0:0] icmp_ln1039_82_fu_1643_p2;
wire   [0:0] icmp_ln1039_83_fu_1652_p2;
wire   [0:0] icmp_ln1039_84_fu_1661_p2;
wire   [0:0] icmp_ln1039_85_fu_1670_p2;
wire   [0:0] icmp_ln1039_86_fu_1679_p2;
wire   [0:0] icmp_ln1039_87_fu_1688_p2;
wire   [0:0] icmp_ln1039_88_fu_1697_p2;
wire   [0:0] icmp_ln1039_89_fu_1706_p2;
wire   [0:0] icmp_ln1039_90_fu_1715_p2;
wire   [0:0] icmp_ln1039_91_fu_1724_p2;
wire   [0:0] icmp_ln1039_92_fu_1733_p2;
wire   [0:0] icmp_ln1039_93_fu_1742_p2;
wire   [0:0] icmp_ln1039_94_fu_1751_p2;
wire   [0:0] icmp_ln1039_95_fu_1760_p2;
wire   [0:0] icmp_ln1039_96_fu_1769_p2;
wire   [0:0] icmp_ln1039_97_fu_1778_p2;
wire   [0:0] icmp_ln1039_98_fu_1787_p2;
wire   [0:0] icmp_ln1039_99_fu_1796_p2;
wire   [0:0] icmp_ln1039_100_fu_1805_p2;
wire   [0:0] icmp_ln1039_101_fu_1814_p2;
wire   [0:0] icmp_ln1039_102_fu_1823_p2;
wire   [0:0] icmp_ln1039_103_fu_1832_p2;
wire   [0:0] icmp_ln1039_104_fu_1841_p2;
wire   [0:0] icmp_ln1039_105_fu_1850_p2;
wire   [0:0] icmp_ln1039_106_fu_1859_p2;
wire   [0:0] icmp_ln1039_107_fu_1868_p2;
wire   [0:0] icmp_ln1039_108_fu_1877_p2;
wire   [0:0] icmp_ln1039_109_fu_1886_p2;
wire   [0:0] icmp_ln1039_110_fu_1895_p2;
wire   [0:0] icmp_ln1039_111_fu_1904_p2;
wire   [0:0] icmp_ln1039_112_fu_1913_p2;
wire   [0:0] icmp_ln1039_113_fu_1922_p2;
wire   [0:0] icmp_ln1039_114_fu_1931_p2;
wire   [0:0] icmp_ln1039_115_fu_1940_p2;
wire   [0:0] icmp_ln1039_116_fu_1949_p2;
wire   [0:0] icmp_ln1039_117_fu_1958_p2;
wire   [0:0] icmp_ln1039_118_fu_1967_p2;
wire   [0:0] icmp_ln1039_119_fu_1976_p2;
wire   [0:0] icmp_ln1039_120_fu_1985_p2;
wire   [0:0] icmp_ln1039_121_fu_1994_p2;
wire   [0:0] icmp_ln1039_122_fu_2003_p2;
wire   [0:0] icmp_ln1039_123_fu_2012_p2;
wire   [0:0] icmp_ln1039_124_fu_2021_p2;
wire   [0:0] icmp_ln1039_125_fu_2030_p2;
wire   [4:0] zext_ln840_25_fu_2045_p1;
wire   [4:0] zext_ln840_18_fu_2042_p1;
wire   [4:0] add_ln840_28_fu_2048_p2;
wire   [4:0] zext_ln840_11_fu_2039_p1;
wire   [4:0] add_ln840_29_fu_2054_p2;
wire   [4:0] zext_ln840_40_fu_2067_p1;
wire   [4:0] zext_ln840_33_fu_2064_p1;
wire   [4:0] add_ln840_44_fu_2070_p2;
wire   [4:0] zext_ln840_55_fu_2083_p1;
wire   [4:0] zext_ln840_48_fu_2080_p1;
wire   [4:0] add_ln840_59_fu_2086_p2;
wire   [5:0] zext_ln840_56_fu_2092_p1;
wire   [5:0] zext_ln840_41_fu_2076_p1;
wire   [5:0] add_ln840_60_fu_2096_p2;
wire   [5:0] zext_ln840_26_fu_2060_p1;
wire   [1:0] zext_ln1039_62_fu_1468_p1;
wire   [1:0] zext_ln1039_63_fu_1477_p1;
wire   [1:0] add_ln840_62_fu_2108_p2;
wire   [1:0] zext_ln1039_64_fu_1486_p1;
wire   [1:0] zext_ln1039_65_fu_1495_p1;
wire   [1:0] add_ln840_63_fu_2118_p2;
wire   [2:0] zext_ln840_59_fu_2124_p1;
wire   [2:0] zext_ln840_58_fu_2114_p1;
wire   [2:0] add_ln840_64_fu_2128_p2;
wire   [1:0] zext_ln1039_66_fu_1504_p1;
wire   [1:0] zext_ln1039_67_fu_1513_p1;
wire   [1:0] add_ln840_65_fu_2138_p2;
wire   [1:0] zext_ln1039_68_fu_1522_p1;
wire   [1:0] zext_ln1039_69_fu_1531_p1;
wire   [1:0] add_ln840_66_fu_2148_p2;
wire   [2:0] zext_ln840_62_fu_2154_p1;
wire   [2:0] zext_ln840_61_fu_2144_p1;
wire   [2:0] add_ln840_67_fu_2158_p2;
wire   [3:0] zext_ln840_63_fu_2164_p1;
wire   [3:0] zext_ln840_60_fu_2134_p1;
wire   [1:0] zext_ln1039_70_fu_1540_p1;
wire   [1:0] zext_ln1039_71_fu_1549_p1;
wire   [1:0] add_ln840_69_fu_2174_p2;
wire   [1:0] zext_ln1039_72_fu_1558_p1;
wire   [1:0] zext_ln1039_73_fu_1567_p1;
wire   [1:0] add_ln840_70_fu_2184_p2;
wire   [2:0] zext_ln840_66_fu_2190_p1;
wire   [2:0] zext_ln840_65_fu_2180_p1;
wire   [2:0] add_ln840_71_fu_2194_p2;
wire   [1:0] zext_ln1039_74_fu_1576_p1;
wire   [1:0] zext_ln1039_75_fu_1585_p1;
wire   [1:0] add_ln840_72_fu_2204_p2;
wire   [1:0] zext_ln1039_76_fu_1594_p1;
wire   [1:0] zext_ln1039_77_fu_1603_p1;
wire   [1:0] add_ln840_73_fu_2214_p2;
wire   [2:0] zext_ln840_69_fu_2220_p1;
wire   [2:0] zext_ln840_68_fu_2210_p1;
wire   [2:0] add_ln840_74_fu_2224_p2;
wire   [3:0] zext_ln840_70_fu_2230_p1;
wire   [3:0] zext_ln840_67_fu_2200_p1;
wire   [1:0] zext_ln1039_78_fu_1612_p1;
wire   [1:0] zext_ln1039_79_fu_1621_p1;
wire   [1:0] add_ln840_77_fu_2240_p2;
wire   [1:0] zext_ln1039_80_fu_1630_p1;
wire   [1:0] zext_ln1039_81_fu_1639_p1;
wire   [1:0] add_ln840_78_fu_2250_p2;
wire   [2:0] zext_ln840_74_fu_2256_p1;
wire   [2:0] zext_ln840_73_fu_2246_p1;
wire   [2:0] add_ln840_79_fu_2260_p2;
wire   [1:0] zext_ln1039_82_fu_1648_p1;
wire   [1:0] zext_ln1039_83_fu_1657_p1;
wire   [1:0] add_ln840_80_fu_2270_p2;
wire   [1:0] zext_ln1039_84_fu_1666_p1;
wire   [1:0] zext_ln1039_85_fu_1675_p1;
wire   [1:0] add_ln840_81_fu_2280_p2;
wire   [2:0] zext_ln840_77_fu_2286_p1;
wire   [2:0] zext_ln840_76_fu_2276_p1;
wire   [2:0] add_ln840_82_fu_2290_p2;
wire   [3:0] zext_ln840_78_fu_2296_p1;
wire   [3:0] zext_ln840_75_fu_2266_p1;
wire   [1:0] zext_ln1039_86_fu_1684_p1;
wire   [1:0] zext_ln1039_87_fu_1693_p1;
wire   [1:0] add_ln840_84_fu_2306_p2;
wire   [1:0] zext_ln1039_88_fu_1702_p1;
wire   [1:0] zext_ln1039_89_fu_1711_p1;
wire   [1:0] add_ln840_85_fu_2316_p2;
wire   [2:0] zext_ln840_81_fu_2322_p1;
wire   [2:0] zext_ln840_80_fu_2312_p1;
wire   [2:0] add_ln840_86_fu_2326_p2;
wire   [1:0] zext_ln1039_90_fu_1720_p1;
wire   [1:0] zext_ln1039_91_fu_1729_p1;
wire   [1:0] add_ln840_87_fu_2336_p2;
wire   [1:0] zext_ln1039_92_fu_1738_p1;
wire   [1:0] zext_ln1039_93_fu_1747_p1;
wire   [1:0] add_ln840_88_fu_2346_p2;
wire   [2:0] zext_ln840_84_fu_2352_p1;
wire   [2:0] zext_ln840_83_fu_2342_p1;
wire   [2:0] add_ln840_89_fu_2356_p2;
wire   [3:0] zext_ln840_85_fu_2362_p1;
wire   [3:0] zext_ln840_82_fu_2332_p1;
wire   [1:0] zext_ln1039_94_fu_1756_p1;
wire   [1:0] zext_ln1039_95_fu_1765_p1;
wire   [1:0] add_ln840_93_fu_2372_p2;
wire   [1:0] zext_ln1039_96_fu_1774_p1;
wire   [1:0] zext_ln1039_97_fu_1783_p1;
wire   [1:0] add_ln840_94_fu_2382_p2;
wire   [2:0] zext_ln840_90_fu_2388_p1;
wire   [2:0] zext_ln840_89_fu_2378_p1;
wire   [2:0] add_ln840_95_fu_2392_p2;
wire   [1:0] zext_ln1039_98_fu_1792_p1;
wire   [1:0] zext_ln1039_99_fu_1801_p1;
wire   [1:0] add_ln840_96_fu_2402_p2;
wire   [1:0] zext_ln1039_100_fu_1810_p1;
wire   [1:0] zext_ln1039_101_fu_1819_p1;
wire   [1:0] add_ln840_97_fu_2412_p2;
wire   [2:0] zext_ln840_93_fu_2418_p1;
wire   [2:0] zext_ln840_92_fu_2408_p1;
wire   [2:0] add_ln840_98_fu_2422_p2;
wire   [3:0] zext_ln840_94_fu_2428_p1;
wire   [3:0] zext_ln840_91_fu_2398_p1;
wire   [1:0] zext_ln1039_102_fu_1828_p1;
wire   [1:0] zext_ln1039_103_fu_1837_p1;
wire   [1:0] add_ln840_100_fu_2438_p2;
wire   [1:0] zext_ln1039_104_fu_1846_p1;
wire   [1:0] zext_ln1039_105_fu_1855_p1;
wire   [1:0] add_ln840_101_fu_2448_p2;
wire   [2:0] zext_ln840_97_fu_2454_p1;
wire   [2:0] zext_ln840_96_fu_2444_p1;
wire   [2:0] add_ln840_102_fu_2458_p2;
wire   [1:0] zext_ln1039_106_fu_1864_p1;
wire   [1:0] zext_ln1039_107_fu_1873_p1;
wire   [1:0] add_ln840_103_fu_2468_p2;
wire   [1:0] zext_ln1039_108_fu_1882_p1;
wire   [1:0] zext_ln1039_109_fu_1891_p1;
wire   [1:0] add_ln840_104_fu_2478_p2;
wire   [2:0] zext_ln840_100_fu_2484_p1;
wire   [2:0] zext_ln840_99_fu_2474_p1;
wire   [2:0] add_ln840_105_fu_2488_p2;
wire   [3:0] zext_ln840_101_fu_2494_p1;
wire   [3:0] zext_ln840_98_fu_2464_p1;
wire   [1:0] zext_ln1039_110_fu_1900_p1;
wire   [1:0] zext_ln1039_111_fu_1909_p1;
wire   [1:0] add_ln840_108_fu_2504_p2;
wire   [1:0] zext_ln1039_112_fu_1918_p1;
wire   [1:0] zext_ln1039_113_fu_1927_p1;
wire   [1:0] add_ln840_109_fu_2514_p2;
wire   [2:0] zext_ln840_105_fu_2520_p1;
wire   [2:0] zext_ln840_104_fu_2510_p1;
wire   [2:0] add_ln840_110_fu_2524_p2;
wire   [1:0] zext_ln1039_114_fu_1936_p1;
wire   [1:0] zext_ln1039_115_fu_1945_p1;
wire   [1:0] add_ln840_111_fu_2534_p2;
wire   [1:0] zext_ln1039_116_fu_1954_p1;
wire   [1:0] zext_ln1039_117_fu_1963_p1;
wire   [1:0] add_ln840_112_fu_2544_p2;
wire   [2:0] zext_ln840_108_fu_2550_p1;
wire   [2:0] zext_ln840_107_fu_2540_p1;
wire   [2:0] add_ln840_113_fu_2554_p2;
wire   [3:0] zext_ln840_109_fu_2560_p1;
wire   [3:0] zext_ln840_106_fu_2530_p1;
wire   [1:0] zext_ln1039_118_fu_1972_p1;
wire   [1:0] zext_ln1039_119_fu_1981_p1;
wire   [1:0] add_ln840_115_fu_2570_p2;
wire   [1:0] zext_ln1039_120_fu_1990_p1;
wire   [1:0] zext_ln1039_121_fu_1999_p1;
wire   [1:0] add_ln840_116_fu_2580_p2;
wire   [2:0] zext_ln840_112_fu_2586_p1;
wire   [2:0] zext_ln840_111_fu_2576_p1;
wire   [2:0] add_ln840_117_fu_2590_p2;
wire   [1:0] zext_ln1039_122_fu_2008_p1;
wire   [1:0] zext_ln1039_123_fu_2017_p1;
wire   [1:0] add_ln840_118_fu_2600_p2;
wire   [1:0] zext_ln840_fu_2035_p1;
wire   [1:0] zext_ln1039_124_fu_2026_p1;
wire   [1:0] add_ln840_119_fu_2610_p2;
wire   [2:0] zext_ln840_115_fu_2616_p1;
wire   [2:0] zext_ln840_114_fu_2606_p1;
wire   [2:0] add_ln840_120_fu_2620_p2;
wire   [3:0] zext_ln840_116_fu_2626_p1;
wire   [3:0] zext_ln840_113_fu_2596_p1;
wire   [4:0] zext_ln840_71_fu_2642_p1;
wire   [4:0] zext_ln840_64_fu_2639_p1;
wire   [4:0] add_ln840_76_fu_2645_p2;
wire   [4:0] zext_ln840_86_fu_2658_p1;
wire   [4:0] zext_ln840_79_fu_2655_p1;
wire   [4:0] add_ln840_91_fu_2661_p2;
wire   [5:0] zext_ln840_87_fu_2667_p1;
wire   [5:0] zext_ln840_72_fu_2651_p1;
wire   [5:0] add_ln840_92_fu_2671_p2;
wire   [4:0] zext_ln840_102_fu_2684_p1;
wire   [4:0] zext_ln840_95_fu_2681_p1;
wire   [4:0] add_ln840_107_fu_2687_p2;
wire   [4:0] zext_ln840_117_fu_2700_p1;
wire   [4:0] zext_ln840_110_fu_2697_p1;
wire   [4:0] add_ln840_122_fu_2703_p2;
wire   [5:0] zext_ln840_118_fu_2709_p1;
wire   [5:0] zext_ln840_103_fu_2693_p1;
wire   [5:0] add_ln840_123_fu_2713_p2;
wire   [6:0] zext_ln840_119_fu_2719_p1;
wire   [6:0] zext_ln840_88_fu_2677_p1;
wire   [6:0] add_ln840_124_fu_2723_p2;
wire   [6:0] zext_ln840_57_fu_2636_p1;
wire   [6:0] result_V_2_fu_2729_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    ap_start_int;
reg    ap_condition_2161;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

Thresholding_Batch_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2161)) begin
        if ((icmp_ln295_fu_329_p2 == 1'd0)) begin
            i_fu_304 <= i_2_fu_335_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_304 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3) & (icmp_ln295_reg_2747_pp0_iter1_reg == 1'd0))) begin
        add_ln840_106_reg_2965 <= add_ln840_106_fu_2498_p2;
        add_ln840_114_reg_2970 <= add_ln840_114_fu_2564_p2;
        add_ln840_121_reg_2975 <= add_ln840_121_fu_2630_p2;
        add_ln840_61_reg_2935 <= add_ln840_61_fu_2102_p2;
        add_ln840_68_reg_2940 <= add_ln840_68_fu_2168_p2;
        add_ln840_75_reg_2945 <= add_ln840_75_fu_2234_p2;
        add_ln840_83_reg_2950 <= add_ln840_83_fu_2300_p2;
        add_ln840_90_reg_2955 <= add_ln840_90_fu_2366_p2;
        add_ln840_99_reg_2960 <= add_ln840_99_fu_2432_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln295_fu_329_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        add_ln840_11_reg_2895 <= add_ln840_11_fu_593_p2;
        add_ln840_1_reg_2875 <= add_ln840_1_fu_529_p2;
        add_ln840_2_reg_2880 <= add_ln840_2_fu_535_p2;
        add_ln840_3_reg_2885 <= add_ln840_3_fu_541_p2;
        add_ln840_8_reg_2890 <= add_ln840_8_fu_567_p2;
        icmp_ln1039_126_reg_2870 <= icmp_ln1039_126_fu_517_p2;
        icmp_ln1039_32_reg_2865 <= icmp_ln1039_32_fu_501_p2;
        inElem_reg_2751 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln295_reg_2747_pp0_iter0_reg == 1'd0))) begin
        add_ln840_13_reg_2900 <= add_ln840_13_fu_1061_p2;
        add_ln840_20_reg_2905 <= add_ln840_20_fu_1127_p2;
        add_ln840_27_reg_2910 <= add_ln840_27_fu_1193_p2;
        add_ln840_36_reg_2915 <= add_ln840_36_fu_1259_p2;
        add_ln840_43_reg_2920 <= add_ln840_43_fu_1325_p2;
        add_ln840_51_reg_2925 <= add_ln840_51_fu_1391_p2;
        add_ln840_58_reg_2930 <= add_ln840_58_fu_1457_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln295_reg_2747 <= icmp_ln295_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln295_reg_2747_pp0_iter1_reg <= icmp_ln295_reg_2747;
        inElem_reg_2751_pp0_iter1_reg <= inElem_reg_2751;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln295_reg_2747_pp0_iter2_reg <= icmp_ln295_reg_2747_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln295_fu_329_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 13'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_304;
    end
end

always @ (*) begin
    if (((icmp_ln295_fu_329_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln295_fu_329_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0))) & (icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else if (((~((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0))) & (icmp_ln295_reg_2747_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign add_ln840_100_fu_2438_p2 = (zext_ln1039_102_fu_1828_p1 + zext_ln1039_103_fu_1837_p1);

assign add_ln840_101_fu_2448_p2 = (zext_ln1039_104_fu_1846_p1 + zext_ln1039_105_fu_1855_p1);

assign add_ln840_102_fu_2458_p2 = (zext_ln840_97_fu_2454_p1 + zext_ln840_96_fu_2444_p1);

assign add_ln840_103_fu_2468_p2 = (zext_ln1039_106_fu_1864_p1 + zext_ln1039_107_fu_1873_p1);

assign add_ln840_104_fu_2478_p2 = (zext_ln1039_108_fu_1882_p1 + zext_ln1039_109_fu_1891_p1);

assign add_ln840_105_fu_2488_p2 = (zext_ln840_100_fu_2484_p1 + zext_ln840_99_fu_2474_p1);

assign add_ln840_106_fu_2498_p2 = (zext_ln840_101_fu_2494_p1 + zext_ln840_98_fu_2464_p1);

assign add_ln840_107_fu_2687_p2 = (zext_ln840_102_fu_2684_p1 + zext_ln840_95_fu_2681_p1);

assign add_ln840_108_fu_2504_p2 = (zext_ln1039_110_fu_1900_p1 + zext_ln1039_111_fu_1909_p1);

assign add_ln840_109_fu_2514_p2 = (zext_ln1039_112_fu_1918_p1 + zext_ln1039_113_fu_1927_p1);

assign add_ln840_10_fu_583_p2 = (zext_ln1039_12_fu_477_p1 + zext_ln1039_13_fu_487_p1);

assign add_ln840_110_fu_2524_p2 = (zext_ln840_105_fu_2520_p1 + zext_ln840_104_fu_2510_p1);

assign add_ln840_111_fu_2534_p2 = (zext_ln1039_114_fu_1936_p1 + zext_ln1039_115_fu_1945_p1);

assign add_ln840_112_fu_2544_p2 = (zext_ln1039_116_fu_1954_p1 + zext_ln1039_117_fu_1963_p1);

assign add_ln840_113_fu_2554_p2 = (zext_ln840_108_fu_2550_p1 + zext_ln840_107_fu_2540_p1);

assign add_ln840_114_fu_2564_p2 = (zext_ln840_109_fu_2560_p1 + zext_ln840_106_fu_2530_p1);

assign add_ln840_115_fu_2570_p2 = (zext_ln1039_118_fu_1972_p1 + zext_ln1039_119_fu_1981_p1);

assign add_ln840_116_fu_2580_p2 = (zext_ln1039_120_fu_1990_p1 + zext_ln1039_121_fu_1999_p1);

assign add_ln840_117_fu_2590_p2 = (zext_ln840_112_fu_2586_p1 + zext_ln840_111_fu_2576_p1);

assign add_ln840_118_fu_2600_p2 = (zext_ln1039_122_fu_2008_p1 + zext_ln1039_123_fu_2017_p1);

assign add_ln840_119_fu_2610_p2 = (zext_ln840_fu_2035_p1 + zext_ln1039_124_fu_2026_p1);

assign add_ln840_11_fu_593_p2 = (zext_ln840_9_fu_589_p1 + zext_ln840_8_fu_579_p1);

assign add_ln840_120_fu_2620_p2 = (zext_ln840_115_fu_2616_p1 + zext_ln840_114_fu_2606_p1);

assign add_ln840_121_fu_2630_p2 = (zext_ln840_116_fu_2626_p1 + zext_ln840_113_fu_2596_p1);

assign add_ln840_122_fu_2703_p2 = (zext_ln840_117_fu_2700_p1 + zext_ln840_110_fu_2697_p1);

assign add_ln840_123_fu_2713_p2 = (zext_ln840_118_fu_2709_p1 + zext_ln840_103_fu_2693_p1);

assign add_ln840_124_fu_2723_p2 = (zext_ln840_119_fu_2719_p1 + zext_ln840_88_fu_2677_p1);

assign add_ln840_12_fu_1055_p2 = (zext_ln840_10_fu_1052_p1 + zext_ln840_7_fu_1049_p1);

assign add_ln840_13_fu_1061_p2 = (add_ln840_12_fu_1055_p2 + zext_ln840_4_fu_1045_p1);

assign add_ln840_14_fu_1067_p2 = (zext_ln1039_14_fu_609_p1 + zext_ln1039_15_fu_613_p1);

assign add_ln840_15_fu_1077_p2 = (zext_ln1039_16_fu_621_p1 + zext_ln1039_17_fu_630_p1);

assign add_ln840_16_fu_1087_p2 = (zext_ln840_13_fu_1083_p1 + zext_ln840_12_fu_1073_p1);

assign add_ln840_17_fu_1097_p2 = (zext_ln1039_18_fu_639_p1 + zext_ln1039_19_fu_648_p1);

assign add_ln840_18_fu_1107_p2 = (zext_ln1039_20_fu_657_p1 + zext_ln1039_21_fu_666_p1);

assign add_ln840_19_fu_1117_p2 = (zext_ln840_16_fu_1113_p1 + zext_ln840_15_fu_1103_p1);

assign add_ln840_1_fu_529_p2 = (add_ln840_fu_523_p2 + zext_ln1039_fu_357_p1);

assign add_ln840_20_fu_1127_p2 = (zext_ln840_17_fu_1123_p1 + zext_ln840_14_fu_1093_p1);

assign add_ln840_21_fu_1133_p2 = (zext_ln1039_22_fu_675_p1 + zext_ln1039_23_fu_684_p1);

assign add_ln840_22_fu_1143_p2 = (zext_ln1039_24_fu_693_p1 + zext_ln1039_25_fu_702_p1);

assign add_ln840_23_fu_1153_p2 = (zext_ln840_20_fu_1149_p1 + zext_ln840_19_fu_1139_p1);

assign add_ln840_24_fu_1163_p2 = (zext_ln1039_26_fu_711_p1 + zext_ln1039_27_fu_720_p1);

assign add_ln840_25_fu_1173_p2 = (zext_ln1039_28_fu_729_p1 + zext_ln1039_29_fu_738_p1);

assign add_ln840_26_fu_1183_p2 = (zext_ln840_23_fu_1179_p1 + zext_ln840_22_fu_1169_p1);

assign add_ln840_27_fu_1193_p2 = (zext_ln840_24_fu_1189_p1 + zext_ln840_21_fu_1159_p1);

assign add_ln840_28_fu_2048_p2 = (zext_ln840_25_fu_2045_p1 + zext_ln840_18_fu_2042_p1);

assign add_ln840_29_fu_2054_p2 = (add_ln840_28_fu_2048_p2 + zext_ln840_11_fu_2039_p1);

assign add_ln840_2_fu_535_p2 = (zext_ln1039_2_fu_377_p1 + zext_ln1039_3_fu_387_p1);

assign add_ln840_30_fu_1199_p2 = (zext_ln1039_30_fu_747_p1 + zext_ln1039_31_fu_756_p1);

assign add_ln840_31_fu_1209_p2 = (zext_ln1039_32_fu_760_p1 + zext_ln1039_33_fu_768_p1);

assign add_ln840_32_fu_1219_p2 = (zext_ln840_28_fu_1215_p1 + zext_ln840_27_fu_1205_p1);

assign add_ln840_33_fu_1229_p2 = (zext_ln1039_34_fu_777_p1 + zext_ln1039_35_fu_786_p1);

assign add_ln840_34_fu_1239_p2 = (zext_ln1039_36_fu_795_p1 + zext_ln1039_37_fu_804_p1);

assign add_ln840_35_fu_1249_p2 = (zext_ln840_31_fu_1245_p1 + zext_ln840_30_fu_1235_p1);

assign add_ln840_36_fu_1259_p2 = (zext_ln840_32_fu_1255_p1 + zext_ln840_29_fu_1225_p1);

assign add_ln840_37_fu_1265_p2 = (zext_ln1039_38_fu_813_p1 + zext_ln1039_39_fu_822_p1);

assign add_ln840_38_fu_1275_p2 = (zext_ln1039_40_fu_831_p1 + zext_ln1039_41_fu_840_p1);

assign add_ln840_39_fu_1285_p2 = (zext_ln840_35_fu_1281_p1 + zext_ln840_34_fu_1271_p1);

assign add_ln840_3_fu_541_p2 = (zext_ln1039_4_fu_397_p1 + zext_ln1039_5_fu_407_p1);

assign add_ln840_40_fu_1295_p2 = (zext_ln1039_42_fu_849_p1 + zext_ln1039_43_fu_858_p1);

assign add_ln840_41_fu_1305_p2 = (zext_ln1039_44_fu_867_p1 + zext_ln1039_45_fu_876_p1);

assign add_ln840_42_fu_1315_p2 = (zext_ln840_38_fu_1311_p1 + zext_ln840_37_fu_1301_p1);

assign add_ln840_43_fu_1325_p2 = (zext_ln840_39_fu_1321_p1 + zext_ln840_36_fu_1291_p1);

assign add_ln840_44_fu_2070_p2 = (zext_ln840_40_fu_2067_p1 + zext_ln840_33_fu_2064_p1);

assign add_ln840_45_fu_1331_p2 = (zext_ln1039_46_fu_885_p1 + zext_ln1039_47_fu_894_p1);

assign add_ln840_46_fu_1341_p2 = (zext_ln1039_48_fu_903_p1 + zext_ln1039_49_fu_912_p1);

assign add_ln840_47_fu_1351_p2 = (zext_ln840_43_fu_1347_p1 + zext_ln840_42_fu_1337_p1);

assign add_ln840_48_fu_1361_p2 = (zext_ln1039_50_fu_921_p1 + zext_ln1039_51_fu_930_p1);

assign add_ln840_49_fu_1371_p2 = (zext_ln1039_52_fu_939_p1 + zext_ln1039_53_fu_948_p1);

assign add_ln840_4_fu_1033_p2 = (zext_ln840_3_fu_1030_p1 + zext_ln840_2_fu_1027_p1);

assign add_ln840_50_fu_1381_p2 = (zext_ln840_46_fu_1377_p1 + zext_ln840_45_fu_1367_p1);

assign add_ln840_51_fu_1391_p2 = (zext_ln840_47_fu_1387_p1 + zext_ln840_44_fu_1357_p1);

assign add_ln840_52_fu_1397_p2 = (zext_ln1039_54_fu_957_p1 + zext_ln1039_55_fu_966_p1);

assign add_ln840_53_fu_1407_p2 = (zext_ln1039_56_fu_975_p1 + zext_ln1039_57_fu_984_p1);

assign add_ln840_54_fu_1417_p2 = (zext_ln840_50_fu_1413_p1 + zext_ln840_49_fu_1403_p1);

assign add_ln840_55_fu_1427_p2 = (zext_ln1039_58_fu_993_p1 + zext_ln1039_59_fu_1002_p1);

assign add_ln840_56_fu_1437_p2 = (zext_ln1039_60_fu_1011_p1 + zext_ln1039_61_fu_1020_p1);

assign add_ln840_57_fu_1447_p2 = (zext_ln840_53_fu_1443_p1 + zext_ln840_52_fu_1433_p1);

assign add_ln840_58_fu_1457_p2 = (zext_ln840_54_fu_1453_p1 + zext_ln840_51_fu_1423_p1);

assign add_ln840_59_fu_2086_p2 = (zext_ln840_55_fu_2083_p1 + zext_ln840_48_fu_2080_p1);

assign add_ln840_5_fu_1039_p2 = (add_ln840_4_fu_1033_p2 + zext_ln840_1_fu_1024_p1);

assign add_ln840_60_fu_2096_p2 = (zext_ln840_56_fu_2092_p1 + zext_ln840_41_fu_2076_p1);

assign add_ln840_61_fu_2102_p2 = (add_ln840_60_fu_2096_p2 + zext_ln840_26_fu_2060_p1);

assign add_ln840_62_fu_2108_p2 = (zext_ln1039_62_fu_1468_p1 + zext_ln1039_63_fu_1477_p1);

assign add_ln840_63_fu_2118_p2 = (zext_ln1039_64_fu_1486_p1 + zext_ln1039_65_fu_1495_p1);

assign add_ln840_64_fu_2128_p2 = (zext_ln840_59_fu_2124_p1 + zext_ln840_58_fu_2114_p1);

assign add_ln840_65_fu_2138_p2 = (zext_ln1039_66_fu_1504_p1 + zext_ln1039_67_fu_1513_p1);

assign add_ln840_66_fu_2148_p2 = (zext_ln1039_68_fu_1522_p1 + zext_ln1039_69_fu_1531_p1);

assign add_ln840_67_fu_2158_p2 = (zext_ln840_62_fu_2154_p1 + zext_ln840_61_fu_2144_p1);

assign add_ln840_68_fu_2168_p2 = (zext_ln840_63_fu_2164_p1 + zext_ln840_60_fu_2134_p1);

assign add_ln840_69_fu_2174_p2 = (zext_ln1039_70_fu_1540_p1 + zext_ln1039_71_fu_1549_p1);

assign add_ln840_6_fu_547_p2 = (zext_ln1039_6_fu_417_p1 + zext_ln1039_7_fu_427_p1);

assign add_ln840_70_fu_2184_p2 = (zext_ln1039_72_fu_1558_p1 + zext_ln1039_73_fu_1567_p1);

assign add_ln840_71_fu_2194_p2 = (zext_ln840_66_fu_2190_p1 + zext_ln840_65_fu_2180_p1);

assign add_ln840_72_fu_2204_p2 = (zext_ln1039_74_fu_1576_p1 + zext_ln1039_75_fu_1585_p1);

assign add_ln840_73_fu_2214_p2 = (zext_ln1039_76_fu_1594_p1 + zext_ln1039_77_fu_1603_p1);

assign add_ln840_74_fu_2224_p2 = (zext_ln840_69_fu_2220_p1 + zext_ln840_68_fu_2210_p1);

assign add_ln840_75_fu_2234_p2 = (zext_ln840_70_fu_2230_p1 + zext_ln840_67_fu_2200_p1);

assign add_ln840_76_fu_2645_p2 = (zext_ln840_71_fu_2642_p1 + zext_ln840_64_fu_2639_p1);

assign add_ln840_77_fu_2240_p2 = (zext_ln1039_78_fu_1612_p1 + zext_ln1039_79_fu_1621_p1);

assign add_ln840_78_fu_2250_p2 = (zext_ln1039_80_fu_1630_p1 + zext_ln1039_81_fu_1639_p1);

assign add_ln840_79_fu_2260_p2 = (zext_ln840_74_fu_2256_p1 + zext_ln840_73_fu_2246_p1);

assign add_ln840_7_fu_557_p2 = (zext_ln1039_8_fu_437_p1 + zext_ln1039_9_fu_447_p1);

assign add_ln840_80_fu_2270_p2 = (zext_ln1039_82_fu_1648_p1 + zext_ln1039_83_fu_1657_p1);

assign add_ln840_81_fu_2280_p2 = (zext_ln1039_84_fu_1666_p1 + zext_ln1039_85_fu_1675_p1);

assign add_ln840_82_fu_2290_p2 = (zext_ln840_77_fu_2286_p1 + zext_ln840_76_fu_2276_p1);

assign add_ln840_83_fu_2300_p2 = (zext_ln840_78_fu_2296_p1 + zext_ln840_75_fu_2266_p1);

assign add_ln840_84_fu_2306_p2 = (zext_ln1039_86_fu_1684_p1 + zext_ln1039_87_fu_1693_p1);

assign add_ln840_85_fu_2316_p2 = (zext_ln1039_88_fu_1702_p1 + zext_ln1039_89_fu_1711_p1);

assign add_ln840_86_fu_2326_p2 = (zext_ln840_81_fu_2322_p1 + zext_ln840_80_fu_2312_p1);

assign add_ln840_87_fu_2336_p2 = (zext_ln1039_90_fu_1720_p1 + zext_ln1039_91_fu_1729_p1);

assign add_ln840_88_fu_2346_p2 = (zext_ln1039_92_fu_1738_p1 + zext_ln1039_93_fu_1747_p1);

assign add_ln840_89_fu_2356_p2 = (zext_ln840_84_fu_2352_p1 + zext_ln840_83_fu_2342_p1);

assign add_ln840_8_fu_567_p2 = (zext_ln840_6_fu_563_p1 + zext_ln840_5_fu_553_p1);

assign add_ln840_90_fu_2366_p2 = (zext_ln840_85_fu_2362_p1 + zext_ln840_82_fu_2332_p1);

assign add_ln840_91_fu_2661_p2 = (zext_ln840_86_fu_2658_p1 + zext_ln840_79_fu_2655_p1);

assign add_ln840_92_fu_2671_p2 = (zext_ln840_87_fu_2667_p1 + zext_ln840_72_fu_2651_p1);

assign add_ln840_93_fu_2372_p2 = (zext_ln1039_94_fu_1756_p1 + zext_ln1039_95_fu_1765_p1);

assign add_ln840_94_fu_2382_p2 = (zext_ln1039_96_fu_1774_p1 + zext_ln1039_97_fu_1783_p1);

assign add_ln840_95_fu_2392_p2 = (zext_ln840_90_fu_2388_p1 + zext_ln840_89_fu_2378_p1);

assign add_ln840_96_fu_2402_p2 = (zext_ln1039_98_fu_1792_p1 + zext_ln1039_99_fu_1801_p1);

assign add_ln840_97_fu_2412_p2 = (zext_ln1039_100_fu_1810_p1 + zext_ln1039_101_fu_1819_p1);

assign add_ln840_98_fu_2422_p2 = (zext_ln840_93_fu_2418_p1 + zext_ln840_92_fu_2408_p1);

assign add_ln840_99_fu_2432_p2 = (zext_ln840_94_fu_2428_p1 + zext_ln840_91_fu_2398_p1);

assign add_ln840_9_fu_573_p2 = (zext_ln1039_10_fu_457_p1 + zext_ln1039_11_fu_467_p1);

assign add_ln840_fu_523_p2 = (zext_ln215_fu_347_p1 + zext_ln1039_1_fu_367_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_2161 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | ((icmp_ln295_reg_2747_pp0_iter2_reg == 1'd0) & (out_V_TREADY == 1'b0)))) | ((icmp_ln295_fu_329_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_2_fu_335_p2 = (ap_sig_allocacmp_i_1 + 13'd1);

assign icmp_ln1039_100_fu_1805_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd193) ? 1'b1 : 1'b0);

assign icmp_ln1039_101_fu_1814_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd195) ? 1'b1 : 1'b0);

assign icmp_ln1039_102_fu_1823_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd197) ? 1'b1 : 1'b0);

assign icmp_ln1039_103_fu_1832_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd199) ? 1'b1 : 1'b0);

assign icmp_ln1039_104_fu_1841_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd201) ? 1'b1 : 1'b0);

assign icmp_ln1039_105_fu_1850_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd202) ? 1'b1 : 1'b0);

assign icmp_ln1039_106_fu_1859_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd204) ? 1'b1 : 1'b0);

assign icmp_ln1039_107_fu_1868_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd206) ? 1'b1 : 1'b0);

assign icmp_ln1039_108_fu_1877_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd208) ? 1'b1 : 1'b0);

assign icmp_ln1039_109_fu_1886_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd210) ? 1'b1 : 1'b0);

assign icmp_ln1039_10_fu_451_p2 = ((in0_V_TDATA > 8'd21) ? 1'b1 : 1'b0);

assign icmp_ln1039_110_fu_1895_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd212) ? 1'b1 : 1'b0);

assign icmp_ln1039_111_fu_1904_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd214) ? 1'b1 : 1'b0);

assign icmp_ln1039_112_fu_1913_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd216) ? 1'b1 : 1'b0);

assign icmp_ln1039_113_fu_1922_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd218) ? 1'b1 : 1'b0);

assign icmp_ln1039_114_fu_1931_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd220) ? 1'b1 : 1'b0);

assign icmp_ln1039_115_fu_1940_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd221) ? 1'b1 : 1'b0);

assign icmp_ln1039_116_fu_1949_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd223) ? 1'b1 : 1'b0);

assign icmp_ln1039_117_fu_1958_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd225) ? 1'b1 : 1'b0);

assign icmp_ln1039_118_fu_1967_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd227) ? 1'b1 : 1'b0);

assign icmp_ln1039_119_fu_1976_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd229) ? 1'b1 : 1'b0);

assign icmp_ln1039_11_fu_461_p2 = ((in0_V_TDATA > 8'd23) ? 1'b1 : 1'b0);

assign icmp_ln1039_120_fu_1985_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd231) ? 1'b1 : 1'b0);

assign icmp_ln1039_121_fu_1994_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd233) ? 1'b1 : 1'b0);

assign icmp_ln1039_122_fu_2003_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd235) ? 1'b1 : 1'b0);

assign icmp_ln1039_123_fu_2012_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd237) ? 1'b1 : 1'b0);

assign icmp_ln1039_124_fu_2021_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd239) ? 1'b1 : 1'b0);

assign icmp_ln1039_125_fu_2030_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd241) ? 1'b1 : 1'b0);

assign icmp_ln1039_126_fu_517_p2 = ((tmp_1_fu_507_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1039_12_fu_471_p2 = ((in0_V_TDATA > 8'd25) ? 1'b1 : 1'b0);

assign icmp_ln1039_13_fu_481_p2 = ((in0_V_TDATA > 8'd27) ? 1'b1 : 1'b0);

assign icmp_ln1039_14_fu_604_p2 = ((inElem_reg_2751 > 8'd29) ? 1'b1 : 1'b0);

assign icmp_ln1039_16_fu_616_p2 = ((inElem_reg_2751 > 8'd33) ? 1'b1 : 1'b0);

assign icmp_ln1039_17_fu_625_p2 = ((inElem_reg_2751 > 8'd35) ? 1'b1 : 1'b0);

assign icmp_ln1039_18_fu_634_p2 = ((inElem_reg_2751 > 8'd37) ? 1'b1 : 1'b0);

assign icmp_ln1039_19_fu_643_p2 = ((inElem_reg_2751 > 8'd39) ? 1'b1 : 1'b0);

assign icmp_ln1039_1_fu_361_p2 = ((in0_V_TDATA > 8'd4) ? 1'b1 : 1'b0);

assign icmp_ln1039_20_fu_652_p2 = ((inElem_reg_2751 > 8'd40) ? 1'b1 : 1'b0);

assign icmp_ln1039_21_fu_661_p2 = ((inElem_reg_2751 > 8'd42) ? 1'b1 : 1'b0);

assign icmp_ln1039_22_fu_670_p2 = ((inElem_reg_2751 > 8'd44) ? 1'b1 : 1'b0);

assign icmp_ln1039_23_fu_679_p2 = ((inElem_reg_2751 > 8'd46) ? 1'b1 : 1'b0);

assign icmp_ln1039_24_fu_688_p2 = ((inElem_reg_2751 > 8'd48) ? 1'b1 : 1'b0);

assign icmp_ln1039_25_fu_697_p2 = ((inElem_reg_2751 > 8'd50) ? 1'b1 : 1'b0);

assign icmp_ln1039_26_fu_706_p2 = ((inElem_reg_2751 > 8'd52) ? 1'b1 : 1'b0);

assign icmp_ln1039_27_fu_715_p2 = ((inElem_reg_2751 > 8'd54) ? 1'b1 : 1'b0);

assign icmp_ln1039_28_fu_724_p2 = ((inElem_reg_2751 > 8'd56) ? 1'b1 : 1'b0);

assign icmp_ln1039_29_fu_733_p2 = ((inElem_reg_2751 > 8'd58) ? 1'b1 : 1'b0);

assign icmp_ln1039_2_fu_371_p2 = ((in0_V_TDATA > 8'd6) ? 1'b1 : 1'b0);

assign icmp_ln1039_30_fu_742_p2 = ((inElem_reg_2751 > 8'd60) ? 1'b1 : 1'b0);

assign icmp_ln1039_31_fu_751_p2 = ((inElem_reg_2751 > 8'd61) ? 1'b1 : 1'b0);

assign icmp_ln1039_32_fu_501_p2 = ((tmp_fu_491_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1039_33_fu_763_p2 = ((inElem_reg_2751 > 8'd65) ? 1'b1 : 1'b0);

assign icmp_ln1039_34_fu_772_p2 = ((inElem_reg_2751 > 8'd67) ? 1'b1 : 1'b0);

assign icmp_ln1039_35_fu_781_p2 = ((inElem_reg_2751 > 8'd69) ? 1'b1 : 1'b0);

assign icmp_ln1039_36_fu_790_p2 = ((inElem_reg_2751 > 8'd71) ? 1'b1 : 1'b0);

assign icmp_ln1039_37_fu_799_p2 = ((inElem_reg_2751 > 8'd73) ? 1'b1 : 1'b0);

assign icmp_ln1039_38_fu_808_p2 = ((inElem_reg_2751 > 8'd75) ? 1'b1 : 1'b0);

assign icmp_ln1039_39_fu_817_p2 = ((inElem_reg_2751 > 8'd77) ? 1'b1 : 1'b0);

assign icmp_ln1039_3_fu_381_p2 = ((in0_V_TDATA > 8'd8) ? 1'b1 : 1'b0);

assign icmp_ln1039_40_fu_826_p2 = ((inElem_reg_2751 > 8'd79) ? 1'b1 : 1'b0);

assign icmp_ln1039_41_fu_835_p2 = ((inElem_reg_2751 > 8'd80) ? 1'b1 : 1'b0);

assign icmp_ln1039_42_fu_844_p2 = ((inElem_reg_2751 > 8'd82) ? 1'b1 : 1'b0);

assign icmp_ln1039_43_fu_853_p2 = ((inElem_reg_2751 > 8'd84) ? 1'b1 : 1'b0);

assign icmp_ln1039_44_fu_862_p2 = ((inElem_reg_2751 > 8'd86) ? 1'b1 : 1'b0);

assign icmp_ln1039_45_fu_871_p2 = ((inElem_reg_2751 > 8'd88) ? 1'b1 : 1'b0);

assign icmp_ln1039_46_fu_880_p2 = ((inElem_reg_2751 > 8'd90) ? 1'b1 : 1'b0);

assign icmp_ln1039_47_fu_889_p2 = ((inElem_reg_2751 > 8'd92) ? 1'b1 : 1'b0);

assign icmp_ln1039_48_fu_898_p2 = ((inElem_reg_2751 > 8'd94) ? 1'b1 : 1'b0);

assign icmp_ln1039_49_fu_907_p2 = ((inElem_reg_2751 > 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln1039_4_fu_391_p2 = ((in0_V_TDATA > 8'd10) ? 1'b1 : 1'b0);

assign icmp_ln1039_50_fu_916_p2 = ((inElem_reg_2751 > 8'd98) ? 1'b1 : 1'b0);

assign icmp_ln1039_51_fu_925_p2 = ((inElem_reg_2751 > 8'd100) ? 1'b1 : 1'b0);

assign icmp_ln1039_52_fu_934_p2 = ((inElem_reg_2751 > 8'd101) ? 1'b1 : 1'b0);

assign icmp_ln1039_53_fu_943_p2 = ((inElem_reg_2751 > 8'd103) ? 1'b1 : 1'b0);

assign icmp_ln1039_54_fu_952_p2 = ((inElem_reg_2751 > 8'd105) ? 1'b1 : 1'b0);

assign icmp_ln1039_55_fu_961_p2 = ((inElem_reg_2751 > 8'd107) ? 1'b1 : 1'b0);

assign icmp_ln1039_56_fu_970_p2 = ((inElem_reg_2751 > 8'd109) ? 1'b1 : 1'b0);

assign icmp_ln1039_57_fu_979_p2 = ((inElem_reg_2751 > 8'd111) ? 1'b1 : 1'b0);

assign icmp_ln1039_58_fu_988_p2 = ((inElem_reg_2751 > 8'd113) ? 1'b1 : 1'b0);

assign icmp_ln1039_59_fu_997_p2 = ((inElem_reg_2751 > 8'd115) ? 1'b1 : 1'b0);

assign icmp_ln1039_5_fu_401_p2 = ((in0_V_TDATA > 8'd12) ? 1'b1 : 1'b0);

assign icmp_ln1039_60_fu_1006_p2 = ((inElem_reg_2751 > 8'd117) ? 1'b1 : 1'b0);

assign icmp_ln1039_61_fu_1015_p2 = ((inElem_reg_2751 > 8'd119) ? 1'b1 : 1'b0);

assign icmp_ln1039_62_fu_1463_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd120) ? 1'b1 : 1'b0);

assign icmp_ln1039_63_fu_1472_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd122) ? 1'b1 : 1'b0);

assign icmp_ln1039_64_fu_1481_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd124) ? 1'b1 : 1'b0);

assign icmp_ln1039_65_fu_1490_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln1039_66_fu_1499_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln1039_67_fu_1508_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd130) ? 1'b1 : 1'b0);

assign icmp_ln1039_68_fu_1517_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd132) ? 1'b1 : 1'b0);

assign icmp_ln1039_69_fu_1526_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd134) ? 1'b1 : 1'b0);

assign icmp_ln1039_6_fu_411_p2 = ((in0_V_TDATA > 8'd14) ? 1'b1 : 1'b0);

assign icmp_ln1039_70_fu_1535_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd136) ? 1'b1 : 1'b0);

assign icmp_ln1039_71_fu_1544_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd138) ? 1'b1 : 1'b0);

assign icmp_ln1039_72_fu_1553_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd140) ? 1'b1 : 1'b0);

assign icmp_ln1039_73_fu_1562_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd141) ? 1'b1 : 1'b0);

assign icmp_ln1039_74_fu_1571_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd143) ? 1'b1 : 1'b0);

assign icmp_ln1039_75_fu_1580_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd145) ? 1'b1 : 1'b0);

assign icmp_ln1039_76_fu_1589_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd147) ? 1'b1 : 1'b0);

assign icmp_ln1039_77_fu_1598_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd149) ? 1'b1 : 1'b0);

assign icmp_ln1039_78_fu_1607_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd151) ? 1'b1 : 1'b0);

assign icmp_ln1039_79_fu_1616_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd153) ? 1'b1 : 1'b0);

assign icmp_ln1039_7_fu_421_p2 = ((in0_V_TDATA > 8'd16) ? 1'b1 : 1'b0);

assign icmp_ln1039_80_fu_1625_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd155) ? 1'b1 : 1'b0);

assign icmp_ln1039_81_fu_1634_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd157) ? 1'b1 : 1'b0);

assign icmp_ln1039_82_fu_1643_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd159) ? 1'b1 : 1'b0);

assign icmp_ln1039_83_fu_1652_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd161) ? 1'b1 : 1'b0);

assign icmp_ln1039_84_fu_1661_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd162) ? 1'b1 : 1'b0);

assign icmp_ln1039_85_fu_1670_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd164) ? 1'b1 : 1'b0);

assign icmp_ln1039_86_fu_1679_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd166) ? 1'b1 : 1'b0);

assign icmp_ln1039_87_fu_1688_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd168) ? 1'b1 : 1'b0);

assign icmp_ln1039_88_fu_1697_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd170) ? 1'b1 : 1'b0);

assign icmp_ln1039_89_fu_1706_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd172) ? 1'b1 : 1'b0);

assign icmp_ln1039_8_fu_431_p2 = ((in0_V_TDATA > 8'd18) ? 1'b1 : 1'b0);

assign icmp_ln1039_90_fu_1715_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd174) ? 1'b1 : 1'b0);

assign icmp_ln1039_91_fu_1724_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd176) ? 1'b1 : 1'b0);

assign icmp_ln1039_92_fu_1733_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd178) ? 1'b1 : 1'b0);

assign icmp_ln1039_93_fu_1742_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd180) ? 1'b1 : 1'b0);

assign icmp_ln1039_94_fu_1751_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd181) ? 1'b1 : 1'b0);

assign icmp_ln1039_95_fu_1760_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd183) ? 1'b1 : 1'b0);

assign icmp_ln1039_96_fu_1769_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd185) ? 1'b1 : 1'b0);

assign icmp_ln1039_97_fu_1778_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd187) ? 1'b1 : 1'b0);

assign icmp_ln1039_98_fu_1787_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd189) ? 1'b1 : 1'b0);

assign icmp_ln1039_99_fu_1796_p2 = ((inElem_reg_2751_pp0_iter1_reg > 8'd191) ? 1'b1 : 1'b0);

assign icmp_ln1039_9_fu_441_p2 = ((in0_V_TDATA > 8'd20) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_351_p2 = ((in0_V_TDATA > 8'd2) ? 1'b1 : 1'b0);

assign icmp_ln295_fu_329_p2 = ((ap_sig_allocacmp_i_1 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln295_reg_2747_pp0_iter0_reg = icmp_ln295_reg_2747;

assign out_V_TDATA = result_V_2_fu_2729_p2;

assign result_V_2_fu_2729_p2 = (add_ln840_124_fu_2723_p2 + zext_ln840_57_fu_2636_p1);

assign result_V_fu_341_p2 = ((in0_V_TDATA != 8'd0) ? 1'b1 : 1'b0);

assign tmp_1_fu_507_p4 = {{in0_V_TDATA[7:6]}};

assign tmp_fu_491_p4 = {{in0_V_TDATA[7:5]}};

assign zext_ln1039_100_fu_1810_p1 = icmp_ln1039_100_fu_1805_p2;

assign zext_ln1039_101_fu_1819_p1 = icmp_ln1039_101_fu_1814_p2;

assign zext_ln1039_102_fu_1828_p1 = icmp_ln1039_102_fu_1823_p2;

assign zext_ln1039_103_fu_1837_p1 = icmp_ln1039_103_fu_1832_p2;

assign zext_ln1039_104_fu_1846_p1 = icmp_ln1039_104_fu_1841_p2;

assign zext_ln1039_105_fu_1855_p1 = icmp_ln1039_105_fu_1850_p2;

assign zext_ln1039_106_fu_1864_p1 = icmp_ln1039_106_fu_1859_p2;

assign zext_ln1039_107_fu_1873_p1 = icmp_ln1039_107_fu_1868_p2;

assign zext_ln1039_108_fu_1882_p1 = icmp_ln1039_108_fu_1877_p2;

assign zext_ln1039_109_fu_1891_p1 = icmp_ln1039_109_fu_1886_p2;

assign zext_ln1039_10_fu_457_p1 = icmp_ln1039_10_fu_451_p2;

assign zext_ln1039_110_fu_1900_p1 = icmp_ln1039_110_fu_1895_p2;

assign zext_ln1039_111_fu_1909_p1 = icmp_ln1039_111_fu_1904_p2;

assign zext_ln1039_112_fu_1918_p1 = icmp_ln1039_112_fu_1913_p2;

assign zext_ln1039_113_fu_1927_p1 = icmp_ln1039_113_fu_1922_p2;

assign zext_ln1039_114_fu_1936_p1 = icmp_ln1039_114_fu_1931_p2;

assign zext_ln1039_115_fu_1945_p1 = icmp_ln1039_115_fu_1940_p2;

assign zext_ln1039_116_fu_1954_p1 = icmp_ln1039_116_fu_1949_p2;

assign zext_ln1039_117_fu_1963_p1 = icmp_ln1039_117_fu_1958_p2;

assign zext_ln1039_118_fu_1972_p1 = icmp_ln1039_118_fu_1967_p2;

assign zext_ln1039_119_fu_1981_p1 = icmp_ln1039_119_fu_1976_p2;

assign zext_ln1039_11_fu_467_p1 = icmp_ln1039_11_fu_461_p2;

assign zext_ln1039_120_fu_1990_p1 = icmp_ln1039_120_fu_1985_p2;

assign zext_ln1039_121_fu_1999_p1 = icmp_ln1039_121_fu_1994_p2;

assign zext_ln1039_122_fu_2008_p1 = icmp_ln1039_122_fu_2003_p2;

assign zext_ln1039_123_fu_2017_p1 = icmp_ln1039_123_fu_2012_p2;

assign zext_ln1039_124_fu_2026_p1 = icmp_ln1039_124_fu_2021_p2;

assign zext_ln1039_12_fu_477_p1 = icmp_ln1039_12_fu_471_p2;

assign zext_ln1039_13_fu_487_p1 = icmp_ln1039_13_fu_481_p2;

assign zext_ln1039_14_fu_609_p1 = icmp_ln1039_14_fu_604_p2;

assign zext_ln1039_15_fu_613_p1 = icmp_ln1039_32_reg_2865;

assign zext_ln1039_16_fu_621_p1 = icmp_ln1039_16_fu_616_p2;

assign zext_ln1039_17_fu_630_p1 = icmp_ln1039_17_fu_625_p2;

assign zext_ln1039_18_fu_639_p1 = icmp_ln1039_18_fu_634_p2;

assign zext_ln1039_19_fu_648_p1 = icmp_ln1039_19_fu_643_p2;

assign zext_ln1039_1_fu_367_p1 = icmp_ln1039_1_fu_361_p2;

assign zext_ln1039_20_fu_657_p1 = icmp_ln1039_20_fu_652_p2;

assign zext_ln1039_21_fu_666_p1 = icmp_ln1039_21_fu_661_p2;

assign zext_ln1039_22_fu_675_p1 = icmp_ln1039_22_fu_670_p2;

assign zext_ln1039_23_fu_684_p1 = icmp_ln1039_23_fu_679_p2;

assign zext_ln1039_24_fu_693_p1 = icmp_ln1039_24_fu_688_p2;

assign zext_ln1039_25_fu_702_p1 = icmp_ln1039_25_fu_697_p2;

assign zext_ln1039_26_fu_711_p1 = icmp_ln1039_26_fu_706_p2;

assign zext_ln1039_27_fu_720_p1 = icmp_ln1039_27_fu_715_p2;

assign zext_ln1039_28_fu_729_p1 = icmp_ln1039_28_fu_724_p2;

assign zext_ln1039_29_fu_738_p1 = icmp_ln1039_29_fu_733_p2;

assign zext_ln1039_2_fu_377_p1 = icmp_ln1039_2_fu_371_p2;

assign zext_ln1039_30_fu_747_p1 = icmp_ln1039_30_fu_742_p2;

assign zext_ln1039_31_fu_756_p1 = icmp_ln1039_31_fu_751_p2;

assign zext_ln1039_32_fu_760_p1 = icmp_ln1039_126_reg_2870;

assign zext_ln1039_33_fu_768_p1 = icmp_ln1039_33_fu_763_p2;

assign zext_ln1039_34_fu_777_p1 = icmp_ln1039_34_fu_772_p2;

assign zext_ln1039_35_fu_786_p1 = icmp_ln1039_35_fu_781_p2;

assign zext_ln1039_36_fu_795_p1 = icmp_ln1039_36_fu_790_p2;

assign zext_ln1039_37_fu_804_p1 = icmp_ln1039_37_fu_799_p2;

assign zext_ln1039_38_fu_813_p1 = icmp_ln1039_38_fu_808_p2;

assign zext_ln1039_39_fu_822_p1 = icmp_ln1039_39_fu_817_p2;

assign zext_ln1039_3_fu_387_p1 = icmp_ln1039_3_fu_381_p2;

assign zext_ln1039_40_fu_831_p1 = icmp_ln1039_40_fu_826_p2;

assign zext_ln1039_41_fu_840_p1 = icmp_ln1039_41_fu_835_p2;

assign zext_ln1039_42_fu_849_p1 = icmp_ln1039_42_fu_844_p2;

assign zext_ln1039_43_fu_858_p1 = icmp_ln1039_43_fu_853_p2;

assign zext_ln1039_44_fu_867_p1 = icmp_ln1039_44_fu_862_p2;

assign zext_ln1039_45_fu_876_p1 = icmp_ln1039_45_fu_871_p2;

assign zext_ln1039_46_fu_885_p1 = icmp_ln1039_46_fu_880_p2;

assign zext_ln1039_47_fu_894_p1 = icmp_ln1039_47_fu_889_p2;

assign zext_ln1039_48_fu_903_p1 = icmp_ln1039_48_fu_898_p2;

assign zext_ln1039_49_fu_912_p1 = icmp_ln1039_49_fu_907_p2;

assign zext_ln1039_4_fu_397_p1 = icmp_ln1039_4_fu_391_p2;

assign zext_ln1039_50_fu_921_p1 = icmp_ln1039_50_fu_916_p2;

assign zext_ln1039_51_fu_930_p1 = icmp_ln1039_51_fu_925_p2;

assign zext_ln1039_52_fu_939_p1 = icmp_ln1039_52_fu_934_p2;

assign zext_ln1039_53_fu_948_p1 = icmp_ln1039_53_fu_943_p2;

assign zext_ln1039_54_fu_957_p1 = icmp_ln1039_54_fu_952_p2;

assign zext_ln1039_55_fu_966_p1 = icmp_ln1039_55_fu_961_p2;

assign zext_ln1039_56_fu_975_p1 = icmp_ln1039_56_fu_970_p2;

assign zext_ln1039_57_fu_984_p1 = icmp_ln1039_57_fu_979_p2;

assign zext_ln1039_58_fu_993_p1 = icmp_ln1039_58_fu_988_p2;

assign zext_ln1039_59_fu_1002_p1 = icmp_ln1039_59_fu_997_p2;

assign zext_ln1039_5_fu_407_p1 = icmp_ln1039_5_fu_401_p2;

assign zext_ln1039_60_fu_1011_p1 = icmp_ln1039_60_fu_1006_p2;

assign zext_ln1039_61_fu_1020_p1 = icmp_ln1039_61_fu_1015_p2;

assign zext_ln1039_62_fu_1468_p1 = icmp_ln1039_62_fu_1463_p2;

assign zext_ln1039_63_fu_1477_p1 = icmp_ln1039_63_fu_1472_p2;

assign zext_ln1039_64_fu_1486_p1 = icmp_ln1039_64_fu_1481_p2;

assign zext_ln1039_65_fu_1495_p1 = icmp_ln1039_65_fu_1490_p2;

assign zext_ln1039_66_fu_1504_p1 = icmp_ln1039_66_fu_1499_p2;

assign zext_ln1039_67_fu_1513_p1 = icmp_ln1039_67_fu_1508_p2;

assign zext_ln1039_68_fu_1522_p1 = icmp_ln1039_68_fu_1517_p2;

assign zext_ln1039_69_fu_1531_p1 = icmp_ln1039_69_fu_1526_p2;

assign zext_ln1039_6_fu_417_p1 = icmp_ln1039_6_fu_411_p2;

assign zext_ln1039_70_fu_1540_p1 = icmp_ln1039_70_fu_1535_p2;

assign zext_ln1039_71_fu_1549_p1 = icmp_ln1039_71_fu_1544_p2;

assign zext_ln1039_72_fu_1558_p1 = icmp_ln1039_72_fu_1553_p2;

assign zext_ln1039_73_fu_1567_p1 = icmp_ln1039_73_fu_1562_p2;

assign zext_ln1039_74_fu_1576_p1 = icmp_ln1039_74_fu_1571_p2;

assign zext_ln1039_75_fu_1585_p1 = icmp_ln1039_75_fu_1580_p2;

assign zext_ln1039_76_fu_1594_p1 = icmp_ln1039_76_fu_1589_p2;

assign zext_ln1039_77_fu_1603_p1 = icmp_ln1039_77_fu_1598_p2;

assign zext_ln1039_78_fu_1612_p1 = icmp_ln1039_78_fu_1607_p2;

assign zext_ln1039_79_fu_1621_p1 = icmp_ln1039_79_fu_1616_p2;

assign zext_ln1039_7_fu_427_p1 = icmp_ln1039_7_fu_421_p2;

assign zext_ln1039_80_fu_1630_p1 = icmp_ln1039_80_fu_1625_p2;

assign zext_ln1039_81_fu_1639_p1 = icmp_ln1039_81_fu_1634_p2;

assign zext_ln1039_82_fu_1648_p1 = icmp_ln1039_82_fu_1643_p2;

assign zext_ln1039_83_fu_1657_p1 = icmp_ln1039_83_fu_1652_p2;

assign zext_ln1039_84_fu_1666_p1 = icmp_ln1039_84_fu_1661_p2;

assign zext_ln1039_85_fu_1675_p1 = icmp_ln1039_85_fu_1670_p2;

assign zext_ln1039_86_fu_1684_p1 = icmp_ln1039_86_fu_1679_p2;

assign zext_ln1039_87_fu_1693_p1 = icmp_ln1039_87_fu_1688_p2;

assign zext_ln1039_88_fu_1702_p1 = icmp_ln1039_88_fu_1697_p2;

assign zext_ln1039_89_fu_1711_p1 = icmp_ln1039_89_fu_1706_p2;

assign zext_ln1039_8_fu_437_p1 = icmp_ln1039_8_fu_431_p2;

assign zext_ln1039_90_fu_1720_p1 = icmp_ln1039_90_fu_1715_p2;

assign zext_ln1039_91_fu_1729_p1 = icmp_ln1039_91_fu_1724_p2;

assign zext_ln1039_92_fu_1738_p1 = icmp_ln1039_92_fu_1733_p2;

assign zext_ln1039_93_fu_1747_p1 = icmp_ln1039_93_fu_1742_p2;

assign zext_ln1039_94_fu_1756_p1 = icmp_ln1039_94_fu_1751_p2;

assign zext_ln1039_95_fu_1765_p1 = icmp_ln1039_95_fu_1760_p2;

assign zext_ln1039_96_fu_1774_p1 = icmp_ln1039_96_fu_1769_p2;

assign zext_ln1039_97_fu_1783_p1 = icmp_ln1039_97_fu_1778_p2;

assign zext_ln1039_98_fu_1792_p1 = icmp_ln1039_98_fu_1787_p2;

assign zext_ln1039_99_fu_1801_p1 = icmp_ln1039_99_fu_1796_p2;

assign zext_ln1039_9_fu_447_p1 = icmp_ln1039_9_fu_441_p2;

assign zext_ln1039_fu_357_p1 = icmp_ln1039_fu_351_p2;

assign zext_ln215_fu_347_p1 = result_V_fu_341_p2;

assign zext_ln840_100_fu_2484_p1 = add_ln840_104_fu_2478_p2;

assign zext_ln840_101_fu_2494_p1 = add_ln840_105_fu_2488_p2;

assign zext_ln840_102_fu_2684_p1 = add_ln840_106_reg_2965;

assign zext_ln840_103_fu_2693_p1 = add_ln840_107_fu_2687_p2;

assign zext_ln840_104_fu_2510_p1 = add_ln840_108_fu_2504_p2;

assign zext_ln840_105_fu_2520_p1 = add_ln840_109_fu_2514_p2;

assign zext_ln840_106_fu_2530_p1 = add_ln840_110_fu_2524_p2;

assign zext_ln840_107_fu_2540_p1 = add_ln840_111_fu_2534_p2;

assign zext_ln840_108_fu_2550_p1 = add_ln840_112_fu_2544_p2;

assign zext_ln840_109_fu_2560_p1 = add_ln840_113_fu_2554_p2;

assign zext_ln840_10_fu_1052_p1 = add_ln840_11_reg_2895;

assign zext_ln840_110_fu_2697_p1 = add_ln840_114_reg_2970;

assign zext_ln840_111_fu_2576_p1 = add_ln840_115_fu_2570_p2;

assign zext_ln840_112_fu_2586_p1 = add_ln840_116_fu_2580_p2;

assign zext_ln840_113_fu_2596_p1 = add_ln840_117_fu_2590_p2;

assign zext_ln840_114_fu_2606_p1 = add_ln840_118_fu_2600_p2;

assign zext_ln840_115_fu_2616_p1 = add_ln840_119_fu_2610_p2;

assign zext_ln840_116_fu_2626_p1 = add_ln840_120_fu_2620_p2;

assign zext_ln840_117_fu_2700_p1 = add_ln840_121_reg_2975;

assign zext_ln840_118_fu_2709_p1 = add_ln840_122_fu_2703_p2;

assign zext_ln840_119_fu_2719_p1 = add_ln840_123_fu_2713_p2;

assign zext_ln840_11_fu_2039_p1 = add_ln840_13_reg_2900;

assign zext_ln840_12_fu_1073_p1 = add_ln840_14_fu_1067_p2;

assign zext_ln840_13_fu_1083_p1 = add_ln840_15_fu_1077_p2;

assign zext_ln840_14_fu_1093_p1 = add_ln840_16_fu_1087_p2;

assign zext_ln840_15_fu_1103_p1 = add_ln840_17_fu_1097_p2;

assign zext_ln840_16_fu_1113_p1 = add_ln840_18_fu_1107_p2;

assign zext_ln840_17_fu_1123_p1 = add_ln840_19_fu_1117_p2;

assign zext_ln840_18_fu_2042_p1 = add_ln840_20_reg_2905;

assign zext_ln840_19_fu_1139_p1 = add_ln840_21_fu_1133_p2;

assign zext_ln840_1_fu_1024_p1 = add_ln840_1_reg_2875;

assign zext_ln840_20_fu_1149_p1 = add_ln840_22_fu_1143_p2;

assign zext_ln840_21_fu_1159_p1 = add_ln840_23_fu_1153_p2;

assign zext_ln840_22_fu_1169_p1 = add_ln840_24_fu_1163_p2;

assign zext_ln840_23_fu_1179_p1 = add_ln840_25_fu_1173_p2;

assign zext_ln840_24_fu_1189_p1 = add_ln840_26_fu_1183_p2;

assign zext_ln840_25_fu_2045_p1 = add_ln840_27_reg_2910;

assign zext_ln840_26_fu_2060_p1 = add_ln840_29_fu_2054_p2;

assign zext_ln840_27_fu_1205_p1 = add_ln840_30_fu_1199_p2;

assign zext_ln840_28_fu_1215_p1 = add_ln840_31_fu_1209_p2;

assign zext_ln840_29_fu_1225_p1 = add_ln840_32_fu_1219_p2;

assign zext_ln840_2_fu_1027_p1 = add_ln840_2_reg_2880;

assign zext_ln840_30_fu_1235_p1 = add_ln840_33_fu_1229_p2;

assign zext_ln840_31_fu_1245_p1 = add_ln840_34_fu_1239_p2;

assign zext_ln840_32_fu_1255_p1 = add_ln840_35_fu_1249_p2;

assign zext_ln840_33_fu_2064_p1 = add_ln840_36_reg_2915;

assign zext_ln840_34_fu_1271_p1 = add_ln840_37_fu_1265_p2;

assign zext_ln840_35_fu_1281_p1 = add_ln840_38_fu_1275_p2;

assign zext_ln840_36_fu_1291_p1 = add_ln840_39_fu_1285_p2;

assign zext_ln840_37_fu_1301_p1 = add_ln840_40_fu_1295_p2;

assign zext_ln840_38_fu_1311_p1 = add_ln840_41_fu_1305_p2;

assign zext_ln840_39_fu_1321_p1 = add_ln840_42_fu_1315_p2;

assign zext_ln840_3_fu_1030_p1 = add_ln840_3_reg_2885;

assign zext_ln840_40_fu_2067_p1 = add_ln840_43_reg_2920;

assign zext_ln840_41_fu_2076_p1 = add_ln840_44_fu_2070_p2;

assign zext_ln840_42_fu_1337_p1 = add_ln840_45_fu_1331_p2;

assign zext_ln840_43_fu_1347_p1 = add_ln840_46_fu_1341_p2;

assign zext_ln840_44_fu_1357_p1 = add_ln840_47_fu_1351_p2;

assign zext_ln840_45_fu_1367_p1 = add_ln840_48_fu_1361_p2;

assign zext_ln840_46_fu_1377_p1 = add_ln840_49_fu_1371_p2;

assign zext_ln840_47_fu_1387_p1 = add_ln840_50_fu_1381_p2;

assign zext_ln840_48_fu_2080_p1 = add_ln840_51_reg_2925;

assign zext_ln840_49_fu_1403_p1 = add_ln840_52_fu_1397_p2;

assign zext_ln840_4_fu_1045_p1 = add_ln840_5_fu_1039_p2;

assign zext_ln840_50_fu_1413_p1 = add_ln840_53_fu_1407_p2;

assign zext_ln840_51_fu_1423_p1 = add_ln840_54_fu_1417_p2;

assign zext_ln840_52_fu_1433_p1 = add_ln840_55_fu_1427_p2;

assign zext_ln840_53_fu_1443_p1 = add_ln840_56_fu_1437_p2;

assign zext_ln840_54_fu_1453_p1 = add_ln840_57_fu_1447_p2;

assign zext_ln840_55_fu_2083_p1 = add_ln840_58_reg_2930;

assign zext_ln840_56_fu_2092_p1 = add_ln840_59_fu_2086_p2;

assign zext_ln840_57_fu_2636_p1 = add_ln840_61_reg_2935;

assign zext_ln840_58_fu_2114_p1 = add_ln840_62_fu_2108_p2;

assign zext_ln840_59_fu_2124_p1 = add_ln840_63_fu_2118_p2;

assign zext_ln840_5_fu_553_p1 = add_ln840_6_fu_547_p2;

assign zext_ln840_60_fu_2134_p1 = add_ln840_64_fu_2128_p2;

assign zext_ln840_61_fu_2144_p1 = add_ln840_65_fu_2138_p2;

assign zext_ln840_62_fu_2154_p1 = add_ln840_66_fu_2148_p2;

assign zext_ln840_63_fu_2164_p1 = add_ln840_67_fu_2158_p2;

assign zext_ln840_64_fu_2639_p1 = add_ln840_68_reg_2940;

assign zext_ln840_65_fu_2180_p1 = add_ln840_69_fu_2174_p2;

assign zext_ln840_66_fu_2190_p1 = add_ln840_70_fu_2184_p2;

assign zext_ln840_67_fu_2200_p1 = add_ln840_71_fu_2194_p2;

assign zext_ln840_68_fu_2210_p1 = add_ln840_72_fu_2204_p2;

assign zext_ln840_69_fu_2220_p1 = add_ln840_73_fu_2214_p2;

assign zext_ln840_6_fu_563_p1 = add_ln840_7_fu_557_p2;

assign zext_ln840_70_fu_2230_p1 = add_ln840_74_fu_2224_p2;

assign zext_ln840_71_fu_2642_p1 = add_ln840_75_reg_2945;

assign zext_ln840_72_fu_2651_p1 = add_ln840_76_fu_2645_p2;

assign zext_ln840_73_fu_2246_p1 = add_ln840_77_fu_2240_p2;

assign zext_ln840_74_fu_2256_p1 = add_ln840_78_fu_2250_p2;

assign zext_ln840_75_fu_2266_p1 = add_ln840_79_fu_2260_p2;

assign zext_ln840_76_fu_2276_p1 = add_ln840_80_fu_2270_p2;

assign zext_ln840_77_fu_2286_p1 = add_ln840_81_fu_2280_p2;

assign zext_ln840_78_fu_2296_p1 = add_ln840_82_fu_2290_p2;

assign zext_ln840_79_fu_2655_p1 = add_ln840_83_reg_2950;

assign zext_ln840_7_fu_1049_p1 = add_ln840_8_reg_2890;

assign zext_ln840_80_fu_2312_p1 = add_ln840_84_fu_2306_p2;

assign zext_ln840_81_fu_2322_p1 = add_ln840_85_fu_2316_p2;

assign zext_ln840_82_fu_2332_p1 = add_ln840_86_fu_2326_p2;

assign zext_ln840_83_fu_2342_p1 = add_ln840_87_fu_2336_p2;

assign zext_ln840_84_fu_2352_p1 = add_ln840_88_fu_2346_p2;

assign zext_ln840_85_fu_2362_p1 = add_ln840_89_fu_2356_p2;

assign zext_ln840_86_fu_2658_p1 = add_ln840_90_reg_2955;

assign zext_ln840_87_fu_2667_p1 = add_ln840_91_fu_2661_p2;

assign zext_ln840_88_fu_2677_p1 = add_ln840_92_fu_2671_p2;

assign zext_ln840_89_fu_2378_p1 = add_ln840_93_fu_2372_p2;

assign zext_ln840_8_fu_579_p1 = add_ln840_9_fu_573_p2;

assign zext_ln840_90_fu_2388_p1 = add_ln840_94_fu_2382_p2;

assign zext_ln840_91_fu_2398_p1 = add_ln840_95_fu_2392_p2;

assign zext_ln840_92_fu_2408_p1 = add_ln840_96_fu_2402_p2;

assign zext_ln840_93_fu_2418_p1 = add_ln840_97_fu_2412_p2;

assign zext_ln840_94_fu_2428_p1 = add_ln840_98_fu_2422_p2;

assign zext_ln840_95_fu_2681_p1 = add_ln840_99_reg_2960;

assign zext_ln840_96_fu_2444_p1 = add_ln840_100_fu_2438_p2;

assign zext_ln840_97_fu_2454_p1 = add_ln840_101_fu_2448_p2;

assign zext_ln840_98_fu_2464_p1 = add_ln840_102_fu_2458_p2;

assign zext_ln840_99_fu_2474_p1 = add_ln840_103_fu_2468_p2;

assign zext_ln840_9_fu_589_p1 = add_ln840_10_fu_583_p2;

assign zext_ln840_fu_2035_p1 = icmp_ln1039_125_fu_2030_p2;

endmodule //Thresholding_Batch_0_Thresholding_Batch
